### ISSUE TITLE
Set up the namservers & zone files cannot be written & zone is not created

### ISSUE THREAD

**Issue by webterror** [WillyXJ/facileManager#338] opened 2016-08-11 14:26 UTC
Hi, WillyXJ,

thank you for this great tool, but we have problems to configure it.

our steps on a new and clean debian 7 64bit system:
1. we installed apache2 & changed port to XXXX
2. we installed mysql
3. we create a mysql user and a database (for facilemanager)
4. we installed bind9 & dnsutils
5. we installed facilemanager in /var/www
   & st up our configs (includes chown & chmod to www-data and permissions to 775)
6. we log on in facile manager

we deleted all samplefiles
we configured the templates SOA & Zones
we want to set up 2 nameserver / ns1 and ns2 / ns1 should be the current host.

BUT we get the message "unknown" & "client not installed" but should be our localhost "ns1" ?!

then we set up our zone file for the "host alias ns1" including the glue records. we set it up as master

BUT the "named.conf.local" etc. are clean ?! facilemanager don't write any zone files or zones. the server is not authoritative !?

the ns2 should be run on a second server with auto update from ns1. how we configure it correctly? which user permissions are needed, so that facilemanager works?

thank your for your time

kind regards 
web

**Comment by WillyXJ** [comment] 2016-08-11 14:51
Hi @webterror - it looks like you did not install the client software on the DNS servers that you want fmDNS to manage.  Please see https://github.com/WillyXJ/facileManager#client-installation.

**Comment by webterror** [comment] 2016-08-11 15:01
Thank your for your message, but we cant find "facileManager/client/facileManager" - this folder don't exist :-( we installed the complete verison of facilemanager 2.3

**Comment by WillyXJ** [comment] 2016-08-11 15:16
When you download and extract http://www.facilemanager.com/download/facilemanager-complete-2.3.tar.gz you should see client and server directories:

```
$ wget http://www.facilemanager.com/download/facilemanager-complete-2.3.tar.gz
...
$ tar xzf facilemanager-complete-2.3.tar.gz
$ ls -1 facileManager/
client
LICENSE
README.md
server
$
```

The server directory is the web interface and the client directory goes on any clients that are to be managed.

**Comment by webterror** [comment] 2016-08-11 15:18
OK we found the client dir and we tried to install it but we get following message:
Testing XX.XX.XX.XX:5000 via https...ok  
Installation failed.  Could not communicate properly with XX.XX.XX.XX:5000.  Failed to access   https://XX.XX.XX.XX:5000/admin-accounts.php?verify.

**Comment by WillyXJ** [comment] 2016-08-11 15:24
Is this now a duplicate of #334?

**Comment by webterror** [comment] 2016-08-11 15:32
XX.XX.XX.XX:5000/admin-accounts.php?verify -->
s:22:"Account is not found. ";

php /usr/local/facileManager/fmDNS/client.php install debug -->
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Installation failed. Could not communicate properly with XX.XX.XX.XX:5000. Failed to access https://XX.XX.XX.XX:5000/admin-accounts.php?verify.

**Comment by webterror** [comment] 2016-08-11 15:36
ok i changed the http port to 80 adn the ssl port to 443 - now the installation work

**Comment by webterror** [comment] 2016-08-11 15:55
ok now the nameserver set up into the controlpanel ... but he is disabled - why?

**Comment by webterror** [comment] 2016-08-11 15:58
The DNS Check says:
Checking ns1.XYZ.TLD (xx.xx.xx.xx):
  Result: NS is not authoritative

**Comment by WillyXJ** [comment] 2016-08-11 16:00
I'm glad to hear the client installer worked for you.  Clients are always added in a disabled state so you can verify its server settings before enabling it.  Once you enable it, then you will need to build the configuration which will populate the client with the data from the server (configuration, zones, etc.).

**Comment by webterror** [comment] 2016-08-11 16:02
how i can activate this server?

**Comment by webterror** [comment] 2016-08-11 16:04
if everything works, my problems are solved, then I write a tutorial / wiki ... :-)

**Comment by WillyXJ** [comment] 2016-08-11 16:06
Config -> Servers

Then click the "enable" icon in the Actions column for the server(s) you wish to enable.

**Comment by webterror** [comment] 2016-08-11 16:14
Ok i find the Option - can you change this icon? like plesk (green circle/ red circle)?
I have a new problem. I can not build the config from the server. the following message appears to me:
Failed: could not access ns1.XYZ.TLD using ssh (tcp/<my-own-shhport>).

**Comment by WillyXJ** [comment] 2016-08-11 16:34
Can you manually ssh to ns1 from your facileManager server using your defined port?  Perhaps you have a firewall blocking the traffic.

**Comment by webterror** [comment] 2016-08-11 16:57
Ok i created a different "sshuser" group for ssh login ... the user "sshuser" from facilemanager is in this group. this user should be able to log on to the server. ssh for root is disabled.

**Comment by webterror** [comment] 2016-08-11 16:57
the firewall like fail2ban is temp. disabled too

**Comment by webterror** [comment] 2016-08-11 16:59
temp- i change the ssh port to 22 - well that did not work

**Comment by webterror** [comment] 2016-08-11 17:05
now i ad the nsshuser to group "sudo" - then i changed the hostname from "ns1.XYZ.TLD" to XX.XX.XX.XX ( my IP)

xx.xx.xx.xx
 --> Configuration Build failed.

mhmm

**Comment by webterror** [comment] 2016-08-11 17:15
temp. i changed te mod to cron. now the main problem is:
the server is not authoritative !?

**Comment by webterror** [comment] 2016-08-11 17:19
Checking ns1.XYZ.TLD (xx.xx.xx.xx):
  Result: No response from name server

**Comment by WillyXJ** [comment] 2016-08-11 18:00
Was the server config build successful on ns1?  If so, what are there any errors in /var/log/fm.log on ns1?

**Comment by webterror** [comment] 2016-08-12 08:26
Good morning :-)
I added following to set up the dns port 53
iptables -A INPUT -m tcp -p tcp --dport 53 -j ACCEPT
the port was disabled
but it dont work

the logs in  /var/log/fm.log show: "no update found" --> ok

netstat -an | grep "LISTEN " shows me
tcp        0      0 127.0.0.1:3306          0.0.0.0:*             LISTEN  
tcp        0      0 xx.xx.xx.xx:53        0.0.0.0:*               LISTEN 
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN  
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN 
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN   
tcp6       0      0 :::80                   :::*                    LISTEN  
tcp6       0      0 :::53                   :::*                    LISTEN  
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:953                 :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN

dig @5.189.133.154 hoststube.de -t AXFR
                                                                                                                                                 
; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> @xx.xx.xx.xx XYZ.TLD -t AXFR  
; (1 server found)                                                                                                                                                    ;; global options: +cmd                                                                                                                                                     ; Transfer failed. 

the transfer is disabled - why? how i can allow the transfer between my servers? I do not want all configuration files manually change. how it work with facilemanager?

**Comment by webterror** [comment] 2016-08-12 08:50
Under "Config" -> "Options" i set up the Attr. "Allow Transfer" as "Value" i added my Ip Adresses of my NS's. The Transfer now ok - but the server is not authoritative.

**Comment by webterror** [comment] 2016-08-15 11:38
Hey WillyXJ,
we installed 2 servers with facileManager 2.3 and the "client-part" on the systems. I set up the 2 NS Server to "Config" -> "Servers". But i get the following error:  "client install required" ?

Our configs of NS 1:

Server Name: ns1.XYZ.TLD
Method: cron
Server Type:      bind9
Config File: /etc/bind/named.conf
Server Root: /var/cache/bind
Zone Dir's: /etc/bind/zones 
Status: activated
Advice:  -----

Our configs of NS 2:

Server Name: ns2.ABC.TLD
Method: cron
Server Type:      bind9
Config File: /etc/bind/named.conf
Server Root: /var/cache/bind
Zone Dir's: /etc/bind/zones 
Status: NOT activated
Advice: "client install required"

Then we have errors with our NS Set like this example:

Checking ns1.XYZ.TLD (xx.xx.xx.xx):
  Result: Wrong NS set found:
    Expected: ns1.XYZ.TLD, ns2.ABC.TLD
    Found   : ns1.XYZ.TLD.XYZ.TLD, ns2.ABC.TLD.ABC.TLD

Checking ns2.XYZ.TLD (xx.xx.xx.xx):
  Result: Wrong NS set found:
    Expected: ns1.XYZ.TLD, ns2.ABC.TLD
    Found   : ns1.XYZ.TLD.XYZ.TLD, ns2.ABC.TLD.ABC.TLD

Our SOA-Template:

Master Server: ns.
Email Adress: hostmaster.
Refresh: 2h
Retry: 1h
Expire: 2w
TTL: 1d
Append Domain: yes
Template Name: default
Make Default Template: yes

Our Zone-Template:

Domain Name: default
Views: All Views
Zone Map: forward
Zone Type: master
clone of (optional): ----
DNS Servers: ns1.XYZ.TLD, xx.xx.xx.xx (ip of ns2)
Make Default Template: yes

The A Records of the Zone-Template:

*     IN    xx.xx.xx.xx (our third, web, mailserver)           Create PTR: no
mail       IN    xx.xx.xx.xx (our third, web, mailserver)           Create PTR: no
webmail    xx.xx.xx.xx (our third, web, mailserver)           Create PTR: no
www      IN    xx.xx.xx.xx (our third, web, mailserver)           Create PTR: no
ns1     IN       xx.xx.xx.xx (the host ip of ns1)           Create PTR: no
ns2     IN    xx.xx.xx.xx (the host ip of ns2)           Create PTR: no

The MX Records of the Zone-Template:

@      IN       10      mail.DFG.TLD        Append Domain: yes

The NS Records of the Zone-Template:

@      IN       ns1.XYZ.TLD        Append Domain: yes
@      IN       ns2.ABC.TLD        Append Domain: yes

The SOA of the Zone-Template:
Select a Template: default

How we can fix this issues? How we can change the permissions for an automatically dns transfer between this server? 

PS: The "installation how to" is almost finished :-)

Thank you for your time!
web

**Comment by webterror** [comment] 2016-08-15 13:31
OK now the NS work :-) But the automated transfer is bugy? the server not available "no client installed" - see post before 

how i can fix this at last?

**Comment by WillyXJ** [comment] 2016-08-15 14:57
In order for successful communication between the client and the fM server, you need a successful installation of the client.  You can either let the client automatically register itself in Config -> Servers by enabling the Setting:

![image](https://cloud.githubusercontent.com/assets/1309591/17668315/e535ec1a-62c5-11e6-93f8-3a6a19238a3d.png)

This means you do not need to manually create any entries in Config -> Servers as the client installer will create them for you.  Or you can manually create the entry and then run the client installer.  If you see "Client install required" then the client installer did not complete successfully.  In your case of NS2, it sounds like the client installer has not run or had failed for some reason.  What is the output of the client install wizard on NS2?

**Comment by webterror** [comment] 2016-08-16 08:27
Hi,
this is our Config for NS1:
![ns1_servers](https://cloud.githubusercontent.com/assets/20971927/17691581/a1981278-6395-11e6-9bc8-ad7916482e82.png)

and this is your Config for NS2:
![ns2_servers](https://cloud.githubusercontent.com/assets/20971927/17691591/b2c78f38-6395-11e6-9141-15969ad3fa0a.png)

"Allow Automatic Client Registrations" is accepted. The client should be properly installed. I used the Setup in Debugmode - no Errors. Under "Admin" -> "Tools" -> "Connection Test" i get follwoing advice: 
Ping: ok
DNS: ok

This is the Setup of NS1:
![installation ns1](https://cloud.githubusercontent.com/assets/20971927/17692210/fdf98792-6398-11e6-986b-7693684e5ce2.png)

This is the Setup of NS2:
Same like NS1 but using SSH to get updates

I created a ssh user: "nsuser" and set the permissions for ssh. the same user exists on ns1 and ns2.

i think the problem is the ssh connection.

**Comment by WillyXJ** [comment] 2016-08-16 12:44
Based on your first screenshots, it looks like you have two instances of facileManager server installed in two different locations and you are trying to connect both clients to both instances.  Please remove one instance and connect both clients to it because fM is designed to have one server installation and the clients can **_only_** connect to **_one_** server instance.  The server can control an unlimited number of clients.  Please correct this before proceeding.

On an unrelated note, the client installer will create the ssh user automatically so you don't have to create it manually.

**Comment by webterror** [comment] 2016-08-16 13:19
ok thank you for this advice.
needs the server ns2 bind? i would install a clean system only with bind and the fmclient.

**Closed** 2016-10-17 22:17 UTC
