### ISSUE TITLE
[ISSUE] Generating new serial number is stuck 

### ISSUE THREAD

**Issue by chandro** [WillyXJ/facileManager#515] opened 2021-01-13 20:59 UTC
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **v4.0.2**
fmDNS Version : **v4.0.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**
when i install a new server it got stuck on serial request.

**(BUG | ISSUE) Steps to reproduce:**
install a new server using 

php /usr/local/facileManager/fmDNS/client.php install

the option of serial is stuck until timeout, if i check server there is a php line also stuck

/opt/cpanel/ea-php70/root/usr/bin/php-cgi /home/*mysite*/public_html/panel/index.php

i have changed php versions and some doesnt work like 7.1 also 5.6

**Comment by WillyXJ** [comment] 2021-01-14 15:27
I've never tested fM with php-cgi and this sounds like it may be an environment issue. Are there any other web server logs that might give some clues? Does your webhost have mod_security enabled and possibly blocking the requests?

**Comment by chandro** [comment] 2021-01-14 17:36
it seems this error was since i upgraded to cloudlinux my main server ( where panel is hosted ) but there is a lot of ways to play with php. let me see if changing the config

ea-7.x (works but need to figure out how correctly.) 
alt-7.x  (not working any of the alt- )


let me keep looking for the error and i will update this issue

**Comment by msilveirabr** [comment] 2021-06-25 03:57
I'm not sure why, but I've been trying to create a script to deploy fM to a new server, provisioning script.
I saw this happen a lot of times, and I don't have a clue of the cause ...
Sometimes this happens event at first client install attempt, fresh provision.

**Comment by WillyXJ** [comment] 2021-09-10 16:57
I think this is potentially a client PHP version issue. I've finally setup an Ubuntu 20.04 client with PHP 7.4 installed an am experiencing the same behavior. No fix yet, but at least it's now reproducible in my test environment.

**Comment by WillyXJ** [comment] 2021-09-10 19:06
A new development environment has proven to reproduce this issue. When the client calls the server to generate a serial number, the server has to search all available servers tables to ensure the serial number is unique. In order to get the table listing, there is a sql query to the information_schema database and the column names have changed from MySQL 5.x to 8.x.  A fix will be included in the next release of fM.

**Comment by chandro** [comment] 2021-09-10 22:28
thanks for the update! =)

**Comment by WillyXJ** [comment] 2021-09-14 20:14
This is now fixed in [fM 4.1.0](http://www.facilemanager.com/download/) and later.

**Closed by WillyXJ** 2021-09-14 20:14 UTC
Labels: Confirmed Bug, fM Core, Fixed in next release
