### ISSUE TITLE
[ISSUE] fm-install-php displays gray screen for step two

### ISSUE THREAD

**Issue by MeCJay12** [WillyXJ/facileManager#417] opened 2018-10-01 02:23 UTC
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.1.1**
{Module Name} Version : **Core so far**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Step two of first time install to pop up

**(BUG | ISSUE) Actual Behavior:**
gray screen

**(BUG | ISSUE) Steps to reproduce:**
go to http://example.com/facileManager and enter database information. If correct, issue appears.

Hello. New to the project. Just started trying to install the server portion tonight and I've had a rough time. I'm doing my install based on [this](https://community.nethserver.org/t/bind9-facilemanager-webui/897) guide. The differences are that I'm on Ubuntu 16.04 and Apache2. To get setup, I did
`sudo tasksel install lamp-server`
`sudo apt-get install php-curl`
`sudo a2enmod rewrite`
I untared and move the server directory's contents to /etc/www/html/facileManager.
I created /etc/apache2/sites-enabled/facilemanager.conf with
`Alias /facileManager /var/www/html/facileManager`
`<Directory "/var/www/html/facileManager">`
`  AllowOverride All`
`</Directory>`
I believe that's everything. I can't find any error code or relevant logs.
Thanks in advance!

**Comment by MeCJay12** [comment] 2018-10-01 17:27
Kinda solved. Deleting the database I made for fM got me going. I deleted the fM user and database. I recreated the fM user (to make sure I had the right permissions but not the database. Going through the install I had to manually install the config.inc.php file then everything start working... Till I broke it another way but I think I know what I did this time.

**Comment by WillyXJ** [comment] 2018-10-01 17:37
Ok, I'm glad you got it working.  I was just about to spin up a test environment to figure out what might've gone wrong.

**Comment by WillyXJ** [comment] 2018-12-15 22:47
I've recently been able to reproduce this in another environment (Ubuntu 18.04).  It seems to be related to sanitize().

**Comment by WillyXJ** [comment] 2019-03-17 01:41
This is now fixed in [fM 3.4](http://www.facilemanager.com/download/) and later.

**Closed by WillyXJ** 2019-03-17 01:41 UTC
Labels: Confirmed Bug, Fixed in next release, fM Core
