### ISSUE TITLE
no fix in 2.1.4 - include 

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#271] opened 2015-12-11 03:21 UTC
Hi,
no fix include in v.2.1.4
link to error (see image) https://yadi.sk/i/SRudCgS2m7qse

You were quick to close, but the error is not corrected:
https://github.com/WillyXJ/facileManager/issues/270

**Comment by WillyXJ** [comment] 2015-12-11 04:35
#270 fixed the issue where include statements defined in zone clauses were not showing up during a server config build. They now show up correctly. However, bind may fail to load if the included file is not present which fmDNS is not responsible for. I don't understand what you are reporting as still broken. Could you please elaborate?

**Comment by mike2m** [comment] 2015-12-11 05:56
does not work, all you can see on the image, but if you do not understand, write the steps:
1. lates update facleManager
2. create zone domain.tld (insert SOA and NS)
3. edit options
4. create Include (/etc/bind/include/test.tld)
5. Update zone:
Your named configuration contains one or more errors:/etc/bind/zones/zones.conf.inside:598: open: /etc/bind/zones/include/test.ltd;: file not found

file /etc/bind/zones/zones.conf.inside:598:
zone "domain.tld" {
	type master;
	file "/etc/bind/zones/master/db.domain.tld.hosts";
};

file /etc/bind/zones/include/test.ltd:
test.tld (-rw-r--r--)

not work!

**Comment by WillyXJ** [comment] 2015-12-11 14:10
Thank you for the steps.  However, I'm still not able to see the problem as the include statement does get built with v2.1.4.  After following your steps 1-5 (and I"m assuming you mean step 5 is to build the server config), I get the following on the DNS server (I even created a view since you are using them):

```
==================================================
/etc/named/zones/zones.conf.internal:
==================================================
// This file was built using fmDNS 2.1.4 on Fri, 11 Dec 2015 14:05:40 +0000 Europe/London

zone "domain.tld" {
	type master;
	file "/etc/named/zones/master/db.domain.tld.hosts";
	include "/tmp/file.txt";
};
```

**Comment by WillyXJ** [comment] 2016-01-03 13:51
Is this still an issue? If so, could you please provide other reproducible steps?

**Comment by WillyXJ** [comment] 2016-04-25 00:14
Closing as this has not been reproduced.

**Closed by WillyXJ** 2016-04-25 00:14 UTC
