### ISSUE TITLE
[BUG] fmDHCP cannot update config server files

### ISSUE THREAD

**Issue by teksetter** [WillyXJ/facileManager#523] opened 2021-02-16 14:42 UTC
Good morning,
i installed the fmDHCP module but the server configuration (dhcpd.conf file) is not updated.
I have verified that the "server_update_config" field of the fm_dhcp_servers table is not updated by the gui.

if I manually force this field of the table, the client correctly retrieves the configuration and writes it to the server configuration file.

Thankyou

Giuseppe

**Comment by WillyXJ** [comment] 2021-02-16 16:09
Hello. Would you please fill out the fields in the "New issue" github form (it should have automatically populated the new issue form with the template)?  There is a lot of information I need from that form (version, reproduction steps, etc.).

Thanks.

**Comment by teksetter** [comment] 2021-04-01 09:32
Hi WillyXJ,
sorry if I answer you just now, but I tried to start from scratch with the configuration of easyManager but the problem reoccurs.

Replace everything between stars with current version of your easyManager and module installations:
fM Version: 4.0.3
fMDHCP Version: 0.4.6

The fMDHCP client module is installed in cron mode.
The insertion of the DHCP records by GUI is done without problems.
When I click on the button to update the server configuration files I get the message:

> dhcp-svr
>  -> This server will be updated on the next cron run.
> All updates have been processed.

I wait for the cron daemon to start but the dhcp server configuration is not updated.
> In the client logs I find "fmDHCP: No updates found."

I have verified that the "server_update_config" field of the fm_dhcp_servers table is not updated by the gui.

if I manually force to "yes" this field of the table, the client correctly retrieves the configuration and writes it to the server configuration file.

Thankyou

Giuseppe

**Comment by twildATgmxde** [comment] 2021-05-20 15:02
Hello Everybody,

I can confirm that behavior absolutely as well the workaround Giuseppe! After the cron Job finished the flag correctly off! 

 @WillyXJ is there a schedule plane of next release?

Many thanks in advance.

regards Thomas

**Comment by twildATgmxde** [comment] 2021-05-21 06:02
Hello Everybody, i found a workaround.

Change the enum structure in table fm_dhcp_servers:

server_update_config | enum('yes', 'no') --> server_update_config | enum('yes', 'no', **'conf'**)

because the core package handles it as _conf_ and no longer as _yes_.

    regards Thomas

**Comment by teksetter** [comment] 2021-05-21 08:38
Great, it works!

**Comment by WillyXJ** [comment] 2021-09-14 20:19
This is now fixed in [fmDHCP 0.5.0](http://www.facilemanager.com/modules/fmdhcp/) and later.

**Closed by WillyXJ** 2021-09-14 20:19 UTC
Labels: Confirmed Bug, Fixed in next release, fmDHCP
