### ISSUE TITLE
[ISSUE] http update sudo requiring tty despite sudoers on debian7

### ISSUE THREAD

**Issue by CrazyLittle** [WillyXJ/facileManager#372] opened 2017-04-11 19:21 UTC
fM Version : v3.0-beta1
fmDNS Version : 3.0-beta1

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

ISSUE Expected Behavior: 
Updates Results
server1.dnsserver.foo
 --> [server1.dnsserver.foo] server reload successful

ISSUE Actual Behavior:
server2.dnsserver.foo
 --> [server2.dnsserver.foo] sudo: no tty present and no askpass program specified
 --> [server2.dnsserver.foo] Config build failed.

ISSUE Steps to reproduce:
Push any change to a fmDNS client running on debian7 (instead of Ubuntu clients which function normally)

The sudoers file already has the appropriate entries:
```
Defaults:www-data  !requiretty
Defaults:www-data  !env_reset
www-data        ALL=(root)      NOPASSWD: /usr/bin/php client.php *
```

Changing the last line in sudoers to the following fixes the issue but is not optimal since it opens full access to php via sudo:
```
www-data        ALL=(root)      NOPASSWD: /usr/bin/php
```

**Comment by WillyXJ** [comment] 2017-04-12 04:00
I suspect the issue is the full path is not included for client.php and so the sudo line does not match. Does the issue get resolved if you change the line to the following?

```
www-data        ALL=(root)      NOPASSWD: /usr/bin/php /usr/local/facileManager/fmDNS/client.php *
```

If so, I'd need to look into why the full path was not included in the client installer.

**Comment by CrazyLittle** [comment] 2017-04-12 04:22
Yep that seems to fix it as well.  The sudoers line is generated here:

```
                        /** Add an entry to sudoers */
                        $sudoers_line = "$user\tALL=(root)\tNOPASSWD: " . findProgram('php') . ' ' . $argv[0] . ' *';
                        addSudoersConfig($module_name, $sudoers_line, $user);
```

But when I ran the installer I did it from the same directory as the client.php file, so $argv[0] might not have the full filepath passed to the installer script.  Yep.  Verified:

```
ns5:/usr/local/facileManager/fmDNS# php foo.php
Array
(
    [0] => foo.php
)
ns:/usr/local/facileManager/fmDNS# php /usr/local/facileManager/fmDNS/foo.php
Array
(
    [0] => /usr/local/facileManager/fmDNS/foo.php
)
ns:/usr/local/facileManager/fmDNS#
```

**Comment by WillyXJ** [comment] 2017-04-12 15:35
Thanks for the confirmation. I've committed a fix which will be included in the next pre-release and later.

**Comment by CrazyLittle** [comment] 2017-04-12 19:32
BTW, my proposed `dirname(__FILE__)` fix doesn't actually work. It just resolves to the filepath of the included functions.php script instead of the full filepath of the calling client.php script.  The complete answer seems to be using [debug_backtrace()](http://php.net/manual/en/function.debug-backtrace.php) and popping off the 'file' element off of the first array member.

**Closed** 2017-04-12 19:39 UTC
Labels: Confirmed Bug, Fixed in next release, fM Core

**Comment by WillyXJ** [comment] 2017-04-15 01:51
This is now fixed in [the latest beta version](http://www.facilemanager.com/download/?t=4) and later.
