### ISSUE TITLE
[ISSUE] LDAP authentication with JumpCloud backend not working

### ISSUE THREAD

**Issue by lravelo** [WillyXJ/facileManager#578] opened 2023-05-24 17:55 UTC
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fmDNSVersion : **5.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Expecting that LDAP users in JumpCloud can authenticate (JumpCloud uses an OpenLDAP type backend)

**(BUG | ISSUE) Actual Behavior:**
Does not authenticate.  The server doesn't even make an attempt to communicate with JumpCloud.  I can see errors in `/var/log/php-fpm/www-error.log` which says the following:

`PHP Notice:  Undefined property: fmdb::$last_result in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 265`

**(BUG | ISSUE) Steps to reproduce:**

- Configured LDAP auth in the UI
- LDAP Server: ldap.jumpcloud.com
- Standard Port: 389
- SSL Port: 636
- Protocol Version: Version 3
- Encryption: TLS
- Certificate File:
- Root CA Certificate:
- Referrals: Enabled
- Distinguished Name (DN): uid=<username>,ou=Users,o=<jumpcloud_org_id>,dc=jumpcloud,dc=com (not sure if the "o=<jumpcloud_org_id>" portion of it might cause issues)
- Require Group Membership: True
- Group Distinguished Name (DN) cn=<group_name>,ou=Users,o=<jumpcloud_org_id>,dc=jumpcloud,dc=com
- Group Member Attribute: member
- Search Start DN: ou=Users,o=<jumpcloud_org_id>,dc=jumpcloud,dc=com
- User Template: admin

This config is pretty typical and I have comparable config on other sources and works just fine.

**Comment by WillyXJ** [comment] 2023-05-31 20:54
I think your DN is missing the <username> placeholder.  It should look like this:

`Distinguished Name (DN): uid=<username>,ou=Users,o=[jumpcloud_org_id],dc=jumpcloud,dc=com`

<username> will be automatically replaced with the username entered at the login page.

**Comment by lravelo** [comment] 2023-05-31 21:32
Hi @WillyXJ this was actually an error on my part. For some reason I forgot to add `<username>` when opening the issue but yet that placeholder is there and it does not work:

![image](https://github.com/WillyXJ/facileManager/assets/17074683/f1cb329f-67f2-4914-85eb-0003f4026107)

**Comment by WillyXJ** [comment] 2023-06-01 15:12
I don't think the issue is your DN at this point.  Have you tried using "memberOf" for the Group Member Attribute?  That is the supported attribute according to https://jumpcloud.com/blog/how-to-connect-your-application-to-ldap.

You could also try authenticating without a required group membership to help isolate where the problem is at.

**Comment by lravelo** [comment] 2023-06-01 15:35
ok so removing the require group membership restriction does allow me to log in.  Doing an ldapsearch of this group shows the following:

![image](https://github.com/WillyXJ/facileManager/assets/17074683/ec67d49f-cbad-4ed0-8c79-70d5af2ec832)

it uses the member attribute.  Not sure if what's going on here is that the query is run against the uid to see what groups the account is a member of.  In that case it would be memberOf.  Despite that, neither option works when using requiring group membership.

**Comment by lravelo** [comment] 2023-06-01 19:34
I tried this fix but no dice. Still the same outcome.  Any sort of debug logging I can enable to see more details?

**Comment by WillyXJ** [comment] 2023-06-01 21:36
Unfortunately there isn't any debug logging with fM for LDAP auth. However, I created another test user and it was unable to authenticate until I gave it bind permissions within JumpCloud (under User Security Settings and Permissions for the user).

<img width="223" alt="image" src="https://github.com/WillyXJ/facileManager/assets/1309591/d003c6bb-fc9f-4937-9910-39540d4a1ba6">

Please ensure this option is checked for your users if you want to require the group membership.

I'll have to consider changing the LDAP auth implementation within fM to utilize a bind account to perform the lookups with instead of relying on the authenticating account to do that.

**Comment by WillyXJ** [comment] 2024-02-10 00:31
This is now fixed in [fM 4.6.0](http://www.facilemanager.com/download/) and later.

**Closed by WillyXJ** 2024-02-10 00:31 UTC
Labels: Confirmed Bug, fM Core, Fixed in next release
