### ISSUE TITLE
[BUG] Unable to Add IPv6 Subnet to ACL

### ISSUE THREAD

**Issue by MeCJay12** [WillyXJ/facileManager#643] opened 2024-12-11 03:23 UTC
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 4.6.2
fmDNS Version : 6.0.6

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Click + next to an existing ACL
Type IPv6 into Matched Address List box
Click Save
Subnet is added to ACL

**(BUG | ISSUE) Actual Behavior:**
After clicking save:

`
Fatal error: Uncaught ArithmeticError: Bit shift by negative number in /var/www/html/fm-modules/fmDNS/functions.php:983 Stack trace: #0 /var/www/html/fm-modules/fmDNS/functions.php(492): checkCIDR('2603:6011:713d:...', '60', 128) #1 /var/www/html/fm-modules/fmDNS/classes/class_acls.php(661): verifyAndCleanAddresses('2603:6011:713d:...') #2 /var/www/html/fm-modules/fmDNS/classes/class_acls.php(71): fm_dns_acls->validatePost(Array) #3 /var/www/html/fm-modules/fmDNS/pages/config-acls.php(34): fm_dns_acls->add(Array) #4 /var/www/html/index.php(57): include('/var/www/html/f...') #5 {main} thrown in /var/www/html/fm-modules/fmDNS/functions.php on line 983
`

**(BUG | ISSUE) Steps to reproduce:**
Click + next to an existing ACL
Type IPv6 into Matched Address List box
Click Save

**Comment by MeCJay12** [comment] 2024-12-11 03:24
Also happens with new ACLs. Can't upgrade to 4.7.0 until fmDNS 7.0.0 is in stable.

**Comment by WillyXJ** [comment] 2024-12-12 18:42
I'm unable to reproduce this with fmDNS 6.2.0 (latest stable).

**Comment by MeCJay12** [comment] 2024-12-12 20:19
I upgraded to 4.7.0 / 6.2.0 to test but I'm experiencing the same issue in addition to the cannot push to client bug. What are some debug steps? I've tried a few IPv6 subnets and the issue is the same every time. I tried different variations including fully expanding the subnet. Individual IPv6 addresses work ok.

**Comment by WillyXJ** [comment] 2024-12-12 22:59
Sorry, my mistake -- I had tested a address and not subnet. I do see that IPv6 subnets throw a fatal error in all versions.

**Comment by WillyXJ** [comment] 2024-12-13 04:37
Until there's a fix, you can comment out https://github.com/WillyXJ/facileManager/blob/d2df1dd843a2f23343bd9b3c0bc7c4cca60caefc/server/fm-modules/fmDNS/functions.php#L501 so you can add your ACL. It just won't provide full validation on the input.

**Comment by MeCJay12** [comment] 2024-12-15 02:06
Works for me. I'll let you close this if you want or keep it open until the bug is fixed.

**Comment by WillyXJ** [comment] 2024-12-31 04:18
This is now fixed in [fmDNS 7.0.0-beta4](https://www.facilemanager.com/modules/fmdns/?t=3) and later.

**Closed by WillyXJ** 2024-12-31 04:18 UTC
Labels: Confirmed Bug, fmDNS, Fixed in next release
