### ISSUE TITLE
Chrome Not Working

### ISSUE THREAD

**Issue by jiffydos** [WillyXJ/facileManager#298] opened 2016-03-28 18:54 UTC
Hello All,

Since about 2.1.4 I am no longer able to use a chrome browser to use facilemanger.  Many of the buttons just do not do anything.  I have tried using chrome on a Windows 10 PC, Windows 8.1 PC and latest MAC OS.  Chrome and the OS are up-to-date in all cases.  Safari and Firefox (on both platforms) work fine, so I'm using that for now.  But, I had planned to deploy this to end users for DNS management.  Not supporting Chrome would be a deal breaker.

Thanks!

**Comment by WillyXJ** [comment] 2016-03-28 19:37
This is the first I've heard of Chrome not working once the user is logged in.  In fact, 95% of the development of fM is done with Chrome.  However, it's done with either Windows 7 or Mac OS 10.6.  Which version(s) of Chrome do you see issues with?

I have confirmed Version 49.0.2623.87 m on Win7 works.

**Comment by jiffydos** [comment] 2016-03-29 12:06
Hello, 

Thanks for your response.  I realize that you primarily use Chrome which is where my confusion lies.  Very odd indeed.

Why such an old version of Mac OS?

My version of Chrome on MAC OS X 10.11.14 is:

Version 50.0.2661.49 beta (64-bit)

My Version of Chrome on Windows 10 is:

Version 49.0.2623.110 m

Both have the same issue.  For example, under forward domains, you cannot click the + sign to add more domains.  You click it and all it does is add a # to the end of the URL and nothing else happens.

Thanks for your help!

Dave

**Comment by WillyXJ** [comment] 2016-03-29 14:47
Hi Dave,

First, I meant Mac OS 10.8 - which is still several years old by now, but in my opinion, it's the last good version and I haven't had a need to upgrade (yet).

Second, I've upgraded Chrome on my Win7 box to 49.0.2683.110 m and the webapp still works.  Adding domains and other things require jQuery (javascript).  Could you please confirm your browser has javascript enabled?

![image](https://cloud.githubusercontent.com/assets/1309591/14112127/b213cd3c-f58a-11e5-8796-eccf15d8ef5b.png)

**Comment by jiffydos** [comment] 2016-03-29 14:55
Interesting…  is there any chance it can be server side?  (Note that it does work fine in the latest Firefox on both machines).

Yes… I do have that enabled on my Chrome browsers:

[cid:9C3950E9-518B-4602-8195-6C601E5AB389]


Dave

On Mar 29, 2016, at 10:47 AM, WillyXJ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dave,

First, I meant Mac OS 10.8 - which is still several years old by now, but in my opinion, it's the last good version and I haven't had a need to upgrade (yet).

Second, I've upgraded Chrome on my Win7 box to 49.0.2683.110 m and the webapp still works. Adding domains and other things require jQuery (javascript). Could you please confirm your browser has javascript enabled?

[image]<https://cloud.githubusercontent.com/assets/1309591/14112127/b213cd3c-f58a-11e5-8796-eccf15d8ef5b.png>

**Comment by WillyXJ** [comment] 2016-03-29 18:28
Hi Dave,

If you watch your web server logs while trying to add a new domain, you should see one or more requests hit your logs if the client (Chrome) does send the request.  You could try using an incognito window to see if that yields different results - this wouldn't be the fix, but perhaps point in the right direction.  Something else you can try is to flush your Chrome browser cache - maybe you have some bad cache.

**Comment by jiffydos** [comment] 2016-03-29 18:56
Hello,

Watching the apache logs show nothing requested at all when clicking the + to add another forward zone…. no matter how many times I click it.

I cleared the browser cache without success and even tried incognito mode, which also did nothing.

Very perplexing.

Dave

On Mar 29, 2016, at 2:29 PM, WillyXJ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dave,

If you watch your web server logs while trying to add a new domain, you should see one or more requests hit your logs if the client (Chrome) does send the request. You could try using an incognito window to see if that yields different results - this wouldn't be the fix, but perhaps point in the right direction. Something else you can try is to flush your Chrome browser cache - maybe you have some bad cache.

**Comment by WillyXJ** [comment] 2016-03-29 20:24
So this is definitely a client-side issue.  On your zones page, could you please view the source and provide me with the <head>...</head> section?

The most important part is these two lines that should be at the end:

```
<script src="/fM/server/fm-modules/facileManager/js/facileManager.php?ver=2.1.5" type="text/javascript" charset="utf-8"></script>
<script src="/fM/server/fm-modules/fmDNS/js/module.php?ver=2.1.8" type="text/javascript" charset="utf-8"></script>
```

Would you be able to provide me with the content of those two scripts as seen by your Chrome browser?

**Comment by peterschen** [comment] 2016-03-30 06:22
I think I had the same problem. The thing is that the webserver answers the request with the wrong content-type. Instead of text/javascript there is something flunky like text coming from the webserver. I've added a ``header("Content-Type: text/javascript");``to those two files and since then it works flawlessly.

**Comment by WillyXJ** [comment] 2016-03-30 16:04
@peterschen Did you put that line just before the `echo` statement?

@jiffydos Could you please test peterschen's fix to see if the issue is resolved?  If so, I'd like to put the fix in the code.

**Comment by peterschen** [comment] 2016-03-30 16:06
I put it between the ``require_once`` and ``echo`` statements.

**Comment by jiffydos** [comment] 2016-03-30 18:12
Hello All,

What two files are we talking about.  Sorry to not understand.

Dave



On Mar 30, 2016, at 12:06 PM, Christoph Petersen <notifications@github.com<mailto:notifications@github.com>> wrote:


I put it between the require_once and echo statements.

**Comment by WillyXJ** [comment] 2016-03-30 18:44
Hi Dave,

On your web server, these two files:

```
<docroot>/server/fm-modules/facileManager/js/facileManager.php
<docroot>/server/fm-modules/fmDNS/js/module.php
```

Please add `header("Content-Type: text/javascript");` between the `require_once` and `echo` statements and see if that resolves the issue you have.

**Comment by jiffydos** [comment] 2016-03-30 18:51
Excellent!  yes!  that fixed it.

Dave



On Mar 30, 2016, at 2:44 PM, WillyXJ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dave,

On your web server, these two files:

<docroot>/server/fm-modules/facileManager/js/facileManager.php
<docroot>/server/fm-modules/fmDNS/js/module.php


Please add header("Content-Type: text/javascript"); between the require_once and echo statements and see if that resolves the issue you have.

**Comment by WillyXJ** [comment] 2016-03-30 19:08
Great! Official fix will be included in the next release.

@jiffydos Thanks for the report!
@peterschen Thanks for the fix!

**Comment by WillyXJ** [comment] 2016-04-25 00:09
v2.2 has been released and contains this fix.

**Closed by WillyXJ** 2016-04-25 00:09 UTC
Labels: Bug, fM Core, fmDNS, fmFirewall, fmSQLPass
