### ISSUE TITLE
[ISSUE] error transferring to the slave server when a zone is in a view (same zone name two views)

### ISSUE THREAD

**Issue by oiLvAcciNe** [WillyXJ/facileManager#562] opened 2022-09-27 17:47 UTC
Hi,

can we take a look at this?

I am trying to accomplish a view setup in bind.
The answer is ok. Based on the "match-clients" acl that i defined.

But i am having a problem while transferring this to the slave server.
The master refuses the transfer ... to the best of my knowledge this is because there is no key setup for masters on the slave.

![image](https://user-images.githubusercontent.com/93989004/178714386-1a47196a-7bf0-4e5e-896b-6f4095fefa74.png)

if i put a key in the master server i can only download the zone from that view where the key is in/matches the allow-transfer

![image](https://user-images.githubusercontent.com/93989004/178733292-ba4651a4-e617-4152-91a1-122fe9d72eb8.png)

![image](https://user-images.githubusercontent.com/93989004/178734267-8e004408-9b96-4ea5-b4ed-94888a5c0773.png)

But 
rndc retransfer nos.nos in external
or 
rndc retransfer nos.nos in external

it will always use internal tsig key specified in the master 

.
.

![image](https://user-images.githubusercontent.com/93989004/178735314-cc7856e8-b450-4b6f-a11d-60bab9623432.png)

.
.
.
if i manualy edit te file to the view/zones ... to include the key in master it all works fine

zones/zones.conf.internal
	masters { 10.156.45.72 key internal; };

zones/zones.conf.external
	masters { 10.156.45.72 key external; };

.
![image](https://user-images.githubusercontent.com/93989004/178735997-36824645-f867-435e-81c4-0847a2939f29.png)
.
.
.
.

My fM version on this lab server is v4.3.0
And fmDNS is v5.2.1

.
.
this img below is also a mannualy edit of the named.conf file to provide a lab 
.
.
![image](https://user-images.githubusercontent.com/93989004/178715848-86d4b940-f2ab-4d0b-9c86-c7f495d6bc2c.png)
.

I have already tried to to some setup/configuration in fmDNS ... and also this steps provided above ... 

But i'm missing something or this is not possible yet in gui. Can you confirm?

A possible solution : ... 
Could we have a entry in the edit view to insert a key value for zone transfer 
(that would be added to the master ip / key slave zone configurating / inside "zones/zones.conf.external" ? ... per example ... )

![image](https://user-images.githubusercontent.com/93989004/178734441-fcf901b7-6405-4753-8478-b496ddf70e64.png)

Regards

_Originally posted by @oiLvAcciNe in https://github.com/WillyXJ/facileManager/issues/512#issuecomment-1183167766_

**Comment by oiLvAcciNe** [comment] 2022-10-18 09:03
related to #512

**Comment by WillyXJ** [comment] 2023-02-15 20:11
Duplicate of #512. Further discussion is in original issue.

**Closed by WillyXJ** 2023-02-15 20:11 UTC
