### ISSUE TITLE
[BUG] fmDNS: def_minimum_version should not be NULL

### ISSUE THREAD

**Issue by gianlucagiacometti** [WillyXJ/facileManager#581] opened 2023-07-03 08:51 UTC
fM Version : **4.5.0**
fmDNS Version : **5.3.3**

When building config:

Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /web/sites/dns.isqweb.it/public/fm-modules/fmDNS/classes/class_buildconf.php on line 2018

I went on upgrading from previous versions, I did not try with a new installation

**Comment by WillyXJ** [comment] 2023-07-07 17:51
What PHP version are you using?

**Comment by WillyXJ** [comment] 2023-08-14 21:21
Duplicate of #583 which has more information.

**Closed by WillyXJ** 2023-08-14 21:21 UTC
