### ISSUE TITLE
Zones appears to not reload when a 'naked' domain name is pointed at an ip

### ISSUE THREAD

**Issue by rberain** [WillyXJ/facileManager#159] opened 2014-10-22 21:01 UTC
Zones appears to not reload when a naked domain name is pointed at an ip

example:
domain.com. IN A 1.2.3.4

what works is:
@ IN A 1.2.3.4

It throws the "unable to reload" error, but it actually reloads the zone.

**Comment by WillyXJ** [comment] 2015-01-13 18:15
Closing due to lack of reproduction steps.

**Closed by WillyXJ** 2015-01-13 18:15 UTC
Labels: bug, fmDNS
