### ISSUE TITLE
[BUG] Error converting TXT record containing email address from db to conf file (serious issue since it may be a dmarc record)

### ISSUE THREAD

**Issue by gianlucagiacometti** [WillyXJ/facileManager#617] opened 2024-03-06 16:59 UTC
facileManager v4.6.1
fmDNS v6.0.3 
PHP 8.1.2

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

I create a TXT record:

Record: _dmarc
TTL: 3600
Value: v=DMARC1; p=quarantine; ri=3600; rua=mailto:postmaster@mydomain.com; ruf=mailto:postmaster@mydomain

**(BUG | ISSUE) Expected Behavior:**

The resulting conf file should be:
_dmarc.mydomain.com.     3600   IN   TXT	("v=DMARC1; p=quarantine; ri=3600; rua=mailto:postmaster@mydomain.com; ruf=mailto:postmaster@mydomain.com")

**(BUG | ISSUE) Actual Behavior:**

The resulting conf file is:
_dmarc.mydomain.com.     3600   IN   TXT	("v=DMARC1; p=quarantine; ri=3600; rua=mailto:postmastermydomain.com.mydomain.com; ruf=mailto:postmastermydomain.com.mydomain.com")

**(BUG | ISSUE) Steps to reproduce:**

Just create the record with a "@". The "@" is stripped away and the domain name is added instead

**Comment by gianlucagiacometti** [comment] 2024-03-06 17:06
PHP 8.1.2

**Comment by gianlucagiacometti** [comment] 2024-03-06 18:17
I found the error and created a pull request

**Comment by WillyXJ** [comment] 2024-03-07 14:04
This is caused by #593 which does want to use @ in the TXT record as the domain name. A new solution will need to be implemented.

**Comment by WillyXJ** [comment] 2024-03-15 20:33
This is now fixed in [fmDNS 6.0.4](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2024-03-15 20:33 UTC
