### ISSUE TITLE
Bug in ver. 2.1.3  in  zone options include statement 

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#270] opened 2015-12-09 02:41 UTC
Hi,
in ver. 2.1.3 no work in zone options include statement (include "file-name";)

**Comment by WillyXJ** [comment] 2015-12-09 14:14
It's not really a bug as it was left out by design. Why would you need to include a separate file within a zone clause outside of fmDNS?

**Comment by WillyXJ** [comment] 2015-12-09 14:49
Confirmed bug.  Will be included in next bug fix release.

**Comment by mike2m** [comment] 2015-12-10 05:02
Hi,
link to error (see image) https://yadi.sk/i/UmX65wQjm7qkD

**Comment by WillyXJ** [comment] 2015-12-11 02:51
v2.1.4 contains the fix.

**Closed by WillyXJ** 2015-12-11 02:51 UTC
Labels: Bug, fmDNS
