### ISSUE TITLE
[BUG] wrong syntax for option check-names in a zone file

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#571] opened 2023-03-01 17:09 UTC
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 4.3.0
fmDNS Version : 5.2.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

generate this config :
zone "example.com" {
        type master;
        file "/etc/bind/zones/master/db.example.com.hosts";
        check-names warn;
}

**(BUG | ISSUE) Actual Behavior:**

generate this config :
zone "example.com" {
        type master;
        file "/etc/bind/zones/master/db.example.com.hosts";
        check-names master warn;
}

then log :

Mar  1 16:37:13 ns2 named[25364]: /etc/bind/zones/zones.conf.common:128: 'master' unexpected
Mar  1 16:37:13 ns2 named[25364]: reloading configuration failed: unexpected token
Mar  1 16:37:13 ns2 rndc[25406]: rndc: 'reload' failed: unexpected token
Mar  1 16:37:13 ns2 systemd[1]: bind9.service: control process exited, code=exited status=1
Mar  1 16:37:13 ns2 systemd[1]: Reload failed for BIND Domain Name Server.

**(BUG | ISSUE) Steps to reproduce:**

add the option "check-names" in the additional options sections of a zone

When we add the option "check-names" in the options of a zone, the interface force to chose (master | slave | response | secondary) which is ok of the option is global on the server but don't work in a zone.

you can see it here : https://docstore.mik.ua/orelly/networking_2ndEd/dns/ch04_05.htm#FOOTNOTE-26 at the bottom of the page

While looking if the bug was allready known, I saw in the changelog that the syntax for this option was corrected for version 1.3 in 2014 but I am using version 5.2

**Comment by WillyXJ** [comment] 2023-03-02 14:53
Have you taken any upgrade paths to get to v5.2? If so, what was your initial version you installed? I’m unable to reproduce this with a new installation of v5.2, but I see an upgrade that potentially could have caused this.

**Comment by cahluor** [comment] 2023-03-02 15:01
hummm, I upgraded from facileManager  3.4.1 with fmDNS 3.4

**Comment by cahluor** [comment] 2023-03-03 07:50
Here is the result :
"def_id";"def_function";"def_option_type";"def_option";"def_type";"def_multiple_values";"def_clause_support";"def_zone_support";"def_dropdown";"def_max_parameters";"def_minimum_version"
"32";"options";"global";"check-names";"( master | slave | response | secondary ) ( warn | fail | ignore )";"no";"Z";"MS";"yes";"1";
"932";"options";"global";"check-names";"( master | slave | response | secondary ) ( warn | fail | ignore )";"no";"O";;"yes";"1";

**Comment by WillyXJ** [comment] 2023-03-10 00:17
This is now fixed in [fmDNS 5.3.0](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2023-03-10 00:17 UTC
Labels: Confirmed Bug, fmDNS, Fixed in next release
