### ISSUE TITLE
Bug: Checkboxes next to zones don't appear

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#256] opened 2015-11-18 20:11 UTC
Hi,

I've noticed that checkboxes don't appear next to zones like they do in Servers so no bulk actions can be done. 

Also, related to the same issue, within Servers > Groups the checkboxes appear but if you try to perform any bulk actions you get an error such as "3 is not a valid serial number" so I guess it's passing the group id and just trying to perform the action rather than finding out the server serials from the group id.

I will mention that I am using the 2.1 beta branch as I needed the fix that you put in the other day so I know you don't officially support it. I can't remember if this issue existed in the 2.0.3 branch as I wasn't using server groups at the time, nor had I noticed the bulk action on zones.

**Comment by WillyXJ** [comment] 2015-11-18 20:34
Regarding the zone checkboxes, can you please confirm all these criteria exist for you? https://github.com/WillyXJ/facileManager/issues/245#issuecomment-140729760

Thanks for the report on server group bulk actions.  I've confirmed the bug and plan to have a fix for the 2.1 release.

**Comment by Lormen** [comment] 2015-11-18 20:39
I can confirm that my zones conform and are reloadable if any changes are made (I just can't force them to). I have been changing the domain_reload flag in the database to do this which then allows all zones to reload. Could you just confirm what you mean by Zone Properties as I don't want to waste your time?

**Comment by WillyXJ** [comment] 2015-11-18 20:51
Hiding the checkbox and reload button per zone when there are no record changes is by design.  Would you mind sharing why you would want/need to reload a zone when there are no changes?  Perhaps something's been overlooked in the logic of fmDNS that needs adjusting.

Zone properties would be anything that appears in this window (including the "additional options" for the zone):

![image](https://cloud.githubusercontent.com/assets/1309591/11253890/4871dc3a-8dfb-11e5-845a-67832e34b292.png)

**Comment by Lormen** [comment] 2015-11-18 20:55
Every zone is now template driven so they are either in Internal, External or Dynamic with the properties needed. 

I thought that the small "reload" button on the right was hidden by design and only appears when the DB has been made aware of a change. I thought the checkboxes on the left of the zones should always be there in case you wish to force a reload of a zone much like you can do for server configs.

**Comment by WillyXJ** [comment] 2015-11-18 22:26
Server group bulk actions has been fixed and will be included in the next build release.

It is by design for the zone checkbox and reload button to show/hide based on DB changes.  Afterall, once a zone is loaded in BIND, the reload command won't do anything unless the serial number changes. In the case of fmDNS, the serial number changes only when there are zone file changes.  In what scenario would you need to reload a zone again without changes?

**Comment by Lormen** [comment] 2015-11-18 22:31
It's a bit of a naughty reason but during my testing periods I have manually deleted/edited the zone files on the server to make sure that I am aiming for the correct solution so having the bulk action reload would have been handy for fmDNS to re-create the files that I had changed manually.

**Comment by Lormen** [comment] 2015-11-18 23:00
I suppose I thought that the force reloads on zones was there for the same reason as on servers, if the DB is aware that they need to be reloaded then the reload icons appear so in my head there would be very little point on having the ability to only reload zones that already need reloading in 3 places, singly via the reload buttons, or all together with the top reload everything button would be enough. That's why I thought it was for forcing a reload of the zone without the DB thinking there is a new change to go live.

**Comment by WillyXJ** [comment] 2015-11-19 14:29
Ok I see your logic. The reason the reload checkboxes exist is in case you have 10 zones in need of a reload and you only want to reload five of them then you can tick all five and reload instead of hitting the reload button individually for five zones.

I'm closing this issue as the server group bulk actions bug is resolved for the next release and the zone reload checkboxes function as designed.

**Closed by WillyXJ** 2015-11-19 14:29 UTC
Labels: Bug, fmDNS
