### ISSUE TITLE
Mismatch in allow-update

### ISSUE THREAD

**Issue by geckeon** [WillyXJ/facileManager#175] opened 2015-02-12 10:45 UTC
Hi,

The allow-update options haven't possibility to use rndc key with following syntax :
allow-update { key rndc-key; }
rndc-key is an ACL with a hmac key.

I already open an issue for allow-query and i think that problem isn't done.
I always an error in conf file : allow-query { 192.168.0.0/16,172.16.0.0/12; };
Your modification is ok in the webui but not in the database.
So i use an ACL.

Geckeon.

**Comment by WillyXJ** [comment] 2015-02-12 14:58
Hi Geckeon,

This is actually a duplicate of #157 which was resolved in the v2.0 branch (currently in beta).

Please update your previous issue with details if it's still an issue (I'd like to keep issues separate).

Thanks!

**Closed by WillyXJ** 2015-02-12 14:58 UTC
Labels: Duplicate, fmDNS

**Comment by geckeon** [comment] 2015-02-13 08:50
I hadn't seen this issue sry.
I have update the other ;)
