### ISSUE TITLE
Faulty zone file

### ISSUE THREAD

**Issue by dialsc** [WillyXJ/facileManager#239] opened 2015-08-13 08:02 UTC
Hi,

I've got a reverse zone with 254 pointer records in it. The first 60 records where created manually over the web application, the rest by using the import tool. The records in the source file used to import all had the following format: 194.5.168.192.in-addr.arpa. IN PTR 194.5.168.192.ip-pool.das.net.

Of course the leading 194 was different for each entry... ;)

Please take a look to the zone file that gets generated by fmDNS to be deployed on the target servers:

===========================================================================
/master/db.5.168.192.in-addr.arpa.rev:
===========================================================================
; This file was built using fmDNS 2.0.3 on Thu, 13 Aug 2015 10:00:43 +0200 Europe/Zurich

$TTL 5m
5.168.192.in-addr.arpa. IN SOA ns.das.net. mail.das.net. (
		2015081358	; Serial
		15m		; Refresh
		3m		; Retry
		1w		; Expire
		5m )		; Negative caching of TTL

; Name servers
5.168.192.in-addr.arpa.        IN   NS   ns.das.net.

; Addresses point to hosts
1.5.168.192.in-addr.arpa.      IN   PTR   1.5.168.192.ip-pool.das.net.
2.5.168.192.in-addr.arpa.      IN   PTR   2.5.168.192.ip-pool.das.net.
3.5.168.192.in-addr.arpa.      IN   PTR   3.5.168.192.ip-pool.das.net.
4.5.168.192.in-addr.arpa.      IN   PTR   4.5.168.192.ip-pool.das.net.
5.5.168.192.in-addr.arpa.      IN   PTR   5.5.168.192.ip-pool.das.net.
6.5.168.192.in-addr.arpa.      IN   PTR   6.5.168.192.ip-pool.das.net.
7.5.168.192.in-addr.arpa.      IN   PTR   7.5.168.192.ip-pool.das.net.
8.5.168.192.in-addr.arpa.      IN   PTR   8.5.168.192.ip-pool.das.net.
9.5.168.192.in-addr.arpa.      IN   PTR   9.5.168.192.ip-pool.das.net.
10.5.168.192.in-addr.arpa.      IN   PTR   10.5.168.192.ip-pool.das.net.
11.5.168.192.in-addr.arpa.      IN   PTR   11.5.168.192.ip-pool.das.net.
12.5.168.192.in-addr.arpa.      IN   PTR   12.5.168.192.ip-pool.das.net.
13.5.168.192.in-addr.arpa.      IN   PTR   13.5.168.192.ip-pool.das.net.
14.5.168.192.in-addr.arpa.      IN   PTR   14.5.168.192.ip-pool.das.net.
15.5.168.192.in-addr.arpa.      IN   PTR   15.5.168.192.ip-pool.das.net.
16.5.168.192.in-addr.arpa.      IN   PTR   16.5.168.192.ip-pool.das.net.
17.5.168.192.in-addr.arpa.      IN   PTR   17.5.168.192.ip-pool.das.net.
18.5.168.192.in-addr.arpa.      IN   PTR   18.5.168.192.ip-pool.das.net.
19.5.168.192.in-addr.arpa.      IN   PTR   19.5.168.192.ip-pool.das.net.
20.5.168.192.in-addr.arpa.      IN   PTR   20.5.168.192.ip-pool.das.net.
21.5.168.192.in-addr.arpa.      IN   PTR   21.5.168.192.ip-pool.das.net.
22.5.168.192.in-addr.arpa.      IN   PTR   22.5.168.192.ip-pool.das.net.
23.5.168.192.in-addr.arpa.      IN   PTR   23.5.168.192.ip-pool.das.net.
24.5.168.192.in-addr.arpa.      IN   PTR   24.5.168.192.ip-pool.das.net.
25.5.168.192.in-addr.arpa.      IN   PTR   25.5.168.192.ip-pool.das.net.
26.5.168.192.in-addr.arpa.      IN   PTR   26.5.168.192.ip-pool.das.net.
27.5.168.192.in-addr.arpa.      IN   PTR   27.5.168.192.ip-pool.das.net.
28.5.168.192.in-addr.arpa.      IN   PTR   28.5.168.192.ip-pool.das.net.
29.5.168.192.in-addr.arpa.      IN   PTR   29.5.168.192.ip-pool.das.net.
30.5.168.192.in-addr.arpa.      IN   PTR   30.5.168.192.ip-pool.das.net.
31.5.168.192.in-addr.arpa.      IN   PTR   31.5.168.192.ip-pool.das.net.
32.5.168.192.in-addr.arpa.      IN   PTR   32.5.168.192.ip-pool.das.net.
33.5.168.192.in-addr.arpa.      IN   PTR   33.5.168.192.ip-pool.das.net.
34.5.168.192.in-addr.arpa.      IN   PTR   34.5.168.192.ip-pool.das.net.
35.5.168.192.in-addr.arpa.      IN   PTR   35.5.168.192.ip-pool.das.net.
36.5.168.192.in-addr.arpa.      IN   PTR   36.5.168.192.ip-pool.das.net.
37.5.168.192.in-addr.arpa.      IN   PTR   37.5.168.192.ip-pool.das.net.
38.5.168.192.in-addr.arpa.      IN   PTR   38.5.168.192.ip-pool.das.net.
39.5.168.192.in-addr.arpa.      IN   PTR   39.5.168.192.ip-pool.das.net.
40.5.168.192.in-addr.arpa.      IN   PTR   40.5.168.192.ip-pool.das.net.
41.5.168.192.in-addr.arpa.      IN   PTR   41.5.168.192.ip-pool.das.net.
42.5.168.192.in-addr.arpa.      IN   PTR   42.5.168.192.ip-pool.das.net.
43.5.168.192.in-addr.arpa.      IN   PTR   43.5.168.192.ip-pool.das.net.
44.5.168.192.in-addr.arpa.      IN   PTR   44.5.168.192.ip-pool.das.net.
45.5.168.192.in-addr.arpa.      IN   PTR   45.5.168.192.ip-pool.das.net.
46.5.168.192.in-addr.arpa.      IN   PTR   46.5.168.192.ip-pool.das.net.
47.5.168.192.in-addr.arpa.      IN   PTR   47.5.168.192.ip-pool.das.net.
48.5.168.192.in-addr.arpa.      IN   PTR   48.5.168.192.ip-pool.das.net.
49.5.168.192.in-addr.arpa.      IN   PTR   49.5.168.192.ip-pool.das.net.
50.5.168.192.in-addr.arpa.      IN   PTR   50.5.168.192.ip-pool.das.net.
51.5.168.192.in-addr.arpa.      IN   PTR   51.5.168.192.ip-pool.das.net.
52.5.168.192.in-addr.arpa.      IN   PTR   52.5.168.192.ip-pool.das.net.
53.5.168.192.in-addr.arpa.      IN   PTR   53.5.168.192.ip-pool.das.net.
54.5.168.192.in-addr.arpa.      IN   PTR   54.5.168.192.ip-pool.das.net.
55.5.168.192.in-addr.arpa.      IN   PTR   55.5.168.192.ip-pool.das.net.
56.5.168.192.in-addr.arpa.      IN   PTR   56.5.168.192.ip-pool.das.net.
57.5.168.192.in-addr.arpa.      IN   PTR   57.5.168.192.ip-pool.das.net.
58.5.168.192.in-addr.arpa.      IN   PTR   58.5.168.192.ip-pool.das.net.
59.5.168.192.in-addr.arpa.      IN   PTR   59.5.168.192.ip-pool.das.net.
60.5.168.192.in-addr.arpa.      IN   PTR   60.5.168.192.ip-pool.das.net.
61                             IN   PTR   61.5.168.192.ip-pool.das.net.
62                             IN   PTR   62.5.168.192.ip-pool.das.net.
63                             IN   PTR   63.5.168.192.ip-pool.das.net.
64                             IN   PTR   64.5.168.192.ip-pool.das.net.
65                             IN   PTR   65.5.168.192.ip-pool.das.net.
66                             IN   PTR   66.5.168.192.ip-pool.das.net.
67                             IN   PTR   67.5.168.192.ip-pool.das.net.
68                             IN   PTR   68.5.168.192.ip-pool.das.net.
69                             IN   PTR   69.5.168.192.ip-pool.das.net.
70                             IN   PTR   70.5.168.192.ip-pool.das.net.
71                             IN   PTR   71.5.168.192.ip-pool.das.net.
72                             IN   PTR   72.5.168.192.ip-pool.das.net.
73                             IN   PTR   73.5.168.192.ip-pool.das.net.
74                             IN   PTR   74.5.168.192.ip-pool.das.net.
75                             IN   PTR   75.5.168.192.ip-pool.das.net.
76                             IN   PTR   76.5.168.192.ip-pool.das.net.
77                             IN   PTR   77.5.168.192.ip-pool.das.net.
78                             IN   PTR   78.5.168.192.ip-pool.das.net.
79                             IN   PTR   79.5.168.192.ip-pool.das.net.
80                             IN   PTR   80.5.168.192.ip-pool.das.net.
81                             IN   PTR   81.5.168.192.ip-pool.das.net.
82                             IN   PTR   82.5.168.192.ip-pool.das.net.
83                             IN   PTR   83.5.168.192.ip-pool.das.net.
84                             IN   PTR   84.5.168.192.ip-pool.das.net.
85                             IN   PTR   85.5.168.192.ip-pool.das.net.
86                             IN   PTR   86.5.168.192.ip-pool.das.net.
87                             IN   PTR   87.5.168.192.ip-pool.das.net.
88                             IN   PTR   88.5.168.192.ip-pool.das.net.
89                             IN   PTR   89.5.168.192.ip-pool.das.net.
90                             IN   PTR   90.5.168.192.ip-pool.das.net.
91                             IN   PTR   91.5.168.192.ip-pool.das.net.
92                             IN   PTR   92.5.168.192.ip-pool.das.net.
93                             IN   PTR   93.5.168.192.ip-pool.das.net.
94                             IN   PTR   94.5.168.192.ip-pool.das.net.
95                             IN   PTR   95.5.168.192.ip-pool.das.net.
96                             IN   PTR   96.5.168.192.ip-pool.das.net.
97                             IN   PTR   97.5.168.192.ip-pool.das.net.
98                             IN   PTR   98.5.168.192.ip-pool.das.net.
99                             IN   PTR   99.5.168.192.ip-pool.das.net.
100                            IN   PTR   100.5.168.192.ip-pool.das.net.
101                            IN   PTR   101.5.168.192.ip-pool.das.net.
102                            IN   PTR   102.5.168.192.ip-pool.das.net.
103                            IN   PTR   103.5.168.192.ip-pool.das.net.
104                            IN   PTR   104.5.168.192.ip-pool.das.net.
105                            IN   PTR   105.5.168.192.ip-pool.das.net.
106                            IN   PTR   106.5.168.192.ip-pool.das.net.
107                            IN   PTR   107.5.168.192.ip-pool.das.net.
108                            IN   PTR   108.5.168.192.ip-pool.das.net.
109                            IN   PTR   109.5.168.192.ip-pool.das.net.
110                            IN   PTR   110.5.168.192.ip-pool.das.net.
111                            IN   PTR   111.5.168.192.ip-pool.das.net.
112                            IN   PTR   112.5.168.192.ip-pool.das.net.
113                            IN   PTR   113.5.168.192.ip-pool.das.net.
114                            IN   PTR   114.5.168.192.ip-pool.das.net.
115                            IN   PTR   115.5.168.192.ip-pool.das.net.
116                            IN   PTR   116.5.168.192.ip-pool.das.net.
117                            IN   PTR   117.5.168.192.ip-pool.das.net.
118                            IN   PTR   118.5.168.192.ip-pool.das.net.
119                            IN   PTR   119.5.168.192.ip-pool.das.net.
120                            IN   PTR   120.5.168.192.ip-pool.das.net.
121                            IN   PTR   121.5.168.192.ip-pool.das.net.
122                            IN   PTR   122.5.168.192.ip-pool.das.net.
123                            IN   PTR   123.5.168.192.ip-pool.das.net.
124                            IN   PTR   124.5.168.192.ip-pool.das.net.
125                            IN   PTR   125.5.168.192.ip-pool.das.net.
126                            IN   PTR   126.5.168.192.ip-pool.das.net.
127                            IN   PTR   127.5.168.192.ip-pool.das.net.
128                            IN   PTR   128.5.168.192.ip-pool.das.net.
129                            IN   PTR   129.5.168.192.ip-pool.das.net.
130                            IN   PTR   130.5.168.192.ip-pool.das.net.
131                            IN   PTR   131.5.168.192.ip-pool.das.net.
132                            IN   PTR   132.5.168.192.ip-pool.das.net.
133                            IN   PTR   133.5.168.192.ip-pool.das.net.
134                            IN   PTR   134.5.168.192.ip-pool.das.net.
135                            IN   PTR   135.5.168.192.ip-pool.das.net.
136                            IN   PTR   136.5.168.192.ip-pool.das.net.
137                            IN   PTR   137.5.168.192.ip-pool.das.net.
138                            IN   PTR   138.5.168.192.ip-pool.das.net.
139                            IN   PTR   139.5.168.192.ip-pool.das.net.
140                            IN   PTR   140.5.168.192.ip-pool.das.net.
141                            IN   PTR   141.5.168.192.ip-pool.das.net.
142                            IN   PTR   142.5.168.192.ip-pool.das.net.
143                            IN   PTR   143.5.168.192.ip-pool.das.net.
144                            IN   PTR   144.5.168.192.ip-pool.das.net.
145                            IN   PTR   145.5.168.192.ip-pool.das.net.
146                            IN   PTR   146.5.168.192.ip-pool.das.net.
147                            IN   PTR   147.5.168.192.ip-pool.das.net.
148                            IN   PTR   148.5.168.192.ip-pool.das.net.
149                            IN   PTR   149.5.168.192.ip-pool.das.net.
150                            IN   PTR   150.5.168.192.ip-pool.das.net.
151                            IN   PTR   151.5.168.192.ip-pool.das.net.
152                            IN   PTR   152.5.168.192.ip-pool.das.net.
153                            IN   PTR   153.5.168.192.ip-pool.das.net.
154                            IN   PTR   154.5.168.192.ip-pool.das.net.
155                            IN   PTR   155.5.168.192.ip-pool.das.net.
156                            IN   PTR   156.5.168.192.ip-pool.das.net.
157                            IN   PTR   157.5.168.192.ip-pool.das.net.
158                            IN   PTR   158.5.168.192.ip-pool.das.net.
159                            IN   PTR   159.5.168.192.ip-pool.das.net.
160                            IN   PTR   160.5.168.192.ip-pool.das.net.
161                            IN   PTR   161.5.168.192.ip-pool.das.net.
162                            IN   PTR   162.5.168.192.ip-pool.das.net.
163                            IN   PTR   163.5.168.192.ip-pool.das.net.
164                            IN   PTR   164.5.168.192.ip-pool.das.net.
165                            IN   PTR   165.5.168.192.ip-pool.das.net.
166                            IN   PTR   166.5.168.192.ip-pool.das.net.
167                            IN   PTR   167.5.168.192.ip-pool.das.net.
168                            IN   PTR   168.5.168.192.ip-pool.das.net.
169                            IN   PTR   169.5.168.192.ip-pool.das.net.
170                            IN   PTR   170.5.168.192.ip-pool.das.net.
171                            IN   PTR   171.5.168.192.ip-pool.das.net.
172                            IN   PTR   172.5.168.192.ip-pool.das.net.
173                            IN   PTR   173.5.168.192.ip-pool.das.net.
174                            IN   PTR   174.5.168.192.ip-pool.das.net.
175                            IN   PTR   175.5.168.192.ip-pool.das.net.
176                            IN   PTR   176.5.168.192.ip-pool.das.net.
177                            IN   PTR   177.5.168.192.ip-pool.das.net.
178                            IN   PTR   178.5.168.192.ip-pool.das.net.
179                            IN   PTR   179.5.168.192.ip-pool.das.net.
180                            IN   PTR   180.5.168.192.ip-pool.das.net.
181                            IN   PTR   181.5.168.192.ip-pool.das.net.
182                            IN   PTR   182.5.168.192.ip-pool.das.net.
183                            IN   PTR   183.5.168.192.ip-pool.das.net.
184                            IN   PTR   184.5.168.192.ip-pool.das.net.
185                            IN   PTR   185.5.168.192.ip-pool.das.net.
186                            IN   PTR   186.5.168.192.ip-pool.das.net.
187                            IN   PTR   187.5.168.192.ip-pool.das.net.
188                            IN   PTR   188.5.168.192.ip-pool.das.net.
189                            IN   PTR   189.5.168.192.ip-pool.das.net.
190                            IN   PTR   190.5.168.192.ip-pool.das.net.
191                            IN   PTR   191.5.168.192.ip-pool.das.net.
192                            IN   PTR   192.5.168.192.ip-pool.das.net.
193                            IN   PTR   193.5.168.192.ip-pool.das.net.
194                            IN   PTR   194.5.168.192.ip-pool.das.net.
195                            IN   PTR   195.5.168.192.ip-pool.das.net.
196                            IN   PTR   196.5.168.192.ip-pool.das.net.
197                            IN   PTR   197.5.168.192.ip-pool.das.net.
198                            IN   PTR   198.5.168.192.ip-pool.das.net.
199                            IN   PTR   199.5.168.192.ip-pool.das.net.
200                            IN   PTR   200.5.168.192.ip-pool.das.net.
201                            IN   PTR   201.5.168.192.ip-pool.das.net.
202                            IN   PTR   202.5.168.192.ip-pool.das.net.
203                            IN   PTR   203.5.168.192.ip-pool.das.net.
204                            IN   PTR   204.5.168.192.ip-pool.das.net.
205                            IN   PTR   205.5.168.192.ip-pool.das.net.
206                            IN   PTR   206.5.168.192.ip-pool.das.net.
207                            IN   PTR   207.5.168.192.ip-pool.das.net.
208                            IN   PTR   208.5.168.192.ip-pool.das.net.
209                            IN   PTR   209.5.168.192.ip-pool.das.net.
210                            IN   PTR   210.5.168.192.ip-pool.das.net.
211                            IN   PTR   211.5.168.192.ip-pool.das.net.
212                            IN   PTR   212.5.168.192.ip-pool.das.net.
213                            IN   PTR   213.5.168.192.ip-pool.das.net.
214                            IN   PTR   214.5.168.192.ip-pool.das.net.
215                            IN   PTR   215.5.168.192.ip-pool.das.net.
216                            IN   PTR   216.5.168.192.ip-pool.das.net.
217                            IN   PTR   217.5.168.192.ip-pool.das.net.
218                            IN   PTR   218.5.168.192.ip-pool.das.net.
219                            IN   PTR   219.5.168.192.ip-pool.das.net.
220                            IN   PTR   220.5.168.192.ip-pool.das.net.
221                            IN   PTR   221.5.168.192.ip-pool.das.net.
222                            IN   PTR   222.5.168.192.ip-pool.das.net.
223                            IN   PTR   223.5.168.192.ip-pool.das.net.
224                            IN   PTR   224.5.168.192.ip-pool.das.net.
225                            IN   PTR   225.5.168.192.ip-pool.das.net.
226                            IN   PTR   226.5.168.192.ip-pool.das.net.
227                            IN   PTR   227.5.168.192.ip-pool.das.net.
228                            IN   PTR   228.5.168.192.ip-pool.das.net.
229                            IN   PTR   229.5.168.192.ip-pool.das.net.
230                            IN   PTR   230.5.168.192.ip-pool.das.net.
231                            IN   PTR   231.5.168.192.ip-pool.das.net.
232                            IN   PTR   232.5.168.192.ip-pool.das.net.
233                            IN   PTR   233.5.168.192.ip-pool.das.net.
234                            IN   PTR   234.5.168.192.ip-pool.das.net.
235                            IN   PTR   235.5.168.192.ip-pool.das.net.
236                            IN   PTR   236.5.168.192.ip-pool.das.net.
237                            IN   PTR   237.5.168.192.ip-pool.das.net.
238                            IN   PTR   238.5.168.192.ip-pool.das.net.
239                            IN   PTR   239.5.168.192.ip-pool.das.net.
240                            IN   PTR   240.5.168.192.ip-pool.das.net.
241                            IN   PTR   241.5.168.192.ip-pool.das.net.
242                            IN   PTR   242.5.168.192.ip-pool.das.net.
243                            IN   PTR   243.5.168.192.ip-pool.das.net.
244                            IN   PTR   244.5.168.192.ip-pool.das.net.
245                            IN   PTR   245.5.168.192.ip-pool.das.net.
246                            IN   PTR   246.5.168.192.ip-pool.das.net.
247                            IN   PTR   247.5.168.192.ip-pool.das.net.
248                            IN   PTR   248.5.168.192.ip-pool.das.net.
249                            IN   PTR   249.5.168.192.ip-pool.das.net.
250                            IN   PTR   250.5.168.192.ip-pool.das.net.
251                            IN   PTR   251.5.168.192.ip-pool.das.net.
252                            IN   PTR   252.5.168.192.ip-pool.das.net.
253                            IN   PTR   253.5.168.192.ip-pool.das.net.
254                            IN   PTR   254.5.168.192.ip-pool.das.net.

Looks somehow weird, doesn't it? The version of fmDNS I'm running is 2.0.3.

Greez,

Dirk

**Comment by dialsc** [comment] 2015-08-13 08:10
Little note: By taking a look to the database I found that for all the records not created manuelly but imprted the flag "record_append" is set to "no".

Further the following columns are different for the imported ones:

1. record_priority
2. record_weight
3. record_port

The different values for this colums are - all the same:

1. Created manuelly: NULL
2. Imported: 0

Looks like some kind of a bug in the import tool, doesn't it?

Greez,

Dirk

**Comment by WillyXJ** [comment] 2015-08-13 13:11
Both styles of the records are valid and the import tool strips the zone name by design so it's not a bug per se, but I'll review it for goofy logic.

**Comment by dialsc** [comment] 2015-08-13 13:52
Oh, I see, sorry. I'm not that familiar with the whole DNS/Bind9 stuff so far. Just started two days ago... ;)

Thanks for the clarification!

Greez,

Dirk

**Comment by WillyXJ** [comment] 2016-04-01 18:04
Closing as there's no bug or goofy logic found.

**Closed by WillyXJ** 2016-04-01 18:04 UTC
