### ISSUE TITLE
[BUG] import verification for CAA record

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#433] opened 2019-03-12 16:40 UTC
Please prefix your issue title with one of the following: [BUG]

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
{fmDNS} Version : **3.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG) Expected Behavior:**

Added a CAA record for my domain. fmDNS should not display any import verification window.

**(BUG ) Actual Behavior:**
fmDNS displays a import verification window (see attached image)

**(BUG) Steps to reproduce:**
add a CAA record to a domain

{i added a CAA record to my domain. Every time i configure this domain fmDNS shows a import verification window. When i click import, fmDNS deletes my CAA record.
![fm-caa](https://user-images.githubusercontent.com/38283101/54218412-d3088680-44ed-11e9-9913-9893c474b83f.png)
}

**Comment by WillyXJ** [comment] 2019-03-12 23:50
Based on the screenshot, it looks like this zone has "Support Dynamic Updates" enabled which would present the import window anytime the zone records will get edited and the zone file on the server is different.  What this is showing is that the CAA record does not exist on the DNS server so it would be deleted (as shown by the Action).  You can skip it or cancel which will not delete the record from the database.  Once you reload the zone (or build the server config), the CAA record would be on the DNS server and no longer be present in this Import window.

**Comment by cm91** [comment] 2019-03-13 06:41
You are right, The option "Support Dynamic Updates" is enabled and your answer makes sense to me.
I
![cm91-caa](https://user-images.githubusercontent.com/38283101/54258530-3b457f80-4563-11e9-9033-6254863c6f3e.png)
 thought the same and checked the zone filre of my server before opening the zones for editing.
The CAA record is present in zone files. fmDNS brings up the import verification window anyway.

**Comment by WillyXJ** [comment] 2019-03-13 14:30
That's interesting and unexpected behavior.  Thanks for the follow-up to confirm the report.

**Comment by cm91** [comment] 2019-03-13 16:27
Thanks for your answer. I checked without the option "Support Dynamic Updates" enabled. The import verification window is not showing up. Unfortunately this is not a workaround for me because sometimes i need to add/delete records via nsupdate. For now it helps to skip import for the CAA record but it would be great if you could have a look at this problem and maybe fix it in a future release.

Thanks & Regards,
Christian

**Comment by WillyXJ** [comment] 2019-03-17 01:38
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2019-03-17 01:38 UTC
Labels: Confirmed Bug, Fixed in next release, fmDNS
