### ISSUE TITLE
Infinite redirection loop on front page

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#351] opened 2016-09-23 00:04 UTC
Hello,
Since my upgrate on last fm Package, i can't access the front page and some other pages

I the console i have the following:
![image](https://cloud.githubusercontent.com/assets/16241429/18769944/a5dc0bfa-8131-11e6-928a-ce91d059adb3.png)

On server apache log i have a dozen times:

**CLIENT_IP** - - [23/Sep/2016:01:58:46 +0200] "GET /dnsManage/ HTTP/1.1" 302 546 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
**SERVER_IP**- - [23/Sep/2016:01:58:46 +0200] "POST /dnsManage/admin-accounts.php?verify HTTP/1.1" 200 3683 "-" "-"
**CLIENT_IP** - - [23/Sep/2016:01:58:46 +0200] "GET /dnsManage/ HTTP/1.1" 302 546 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
....

**Comment by WillyXJ** [comment] 2016-10-03 21:49
Even though this issue was opened first, I'm closing it as a duplicate of #353 as the latter has more activity.

**Closed by WillyXJ** 2016-10-03 21:49 UTC
Labels: Duplicate
