### ISSUE TITLE
SOA Serial no incrementing after records being added (A or CNAME).

### ISSUE THREAD

**Issue by aredan** [WillyXJ/facileManager#315] opened 2016-05-03 14:16 UTC
I just installed facileManager and enable the DNS module, installed the client on 2 Debian servers. all this is for my internal network so no request from outside.

setup a test zone and build config for the 2 servers, after a few changes I noticed that the reload is always present and the Serial number (2016050300) is not being updated after a new A or CNAME record is added.

Downloaded the full package so I think that all the software is 2.2+

**Comment by WillyXJ** [comment] 2016-05-03 15:03
So far I'm not able to reproduce this issue (tested with regular zones, clones, and templates).  After you've built the server config for your DNS servers, added a record to a (built) zone, are you reloading the zone?  The SOA serial numbers don't increment unless you reload the zone _**and **_there are no reload errors.  If you are reloading, are there any reload errors reported?

**Comment by aredan** [comment] 2016-05-03 15:48
No errors after hitting _reload_icon in the Zones->forward.

I created the zone today and the Serial is always 2015050300.

![2016-05-03 11_34_48-forward zones facilemanager](https://cloud.githubusercontent.com/assets/939894/14989185/a5c6496e-1124-11e6-8445-b78f35ec65f0.png)
![2016-05-03 11_35_08-forward zones facilemanager](https://cloud.githubusercontent.com/assets/939894/14989196/ae3444e8-1124-11e6-8112-8ec8485e6e3f.png)
![2016-05-03 11_35_46-remote desktop manager free jumper](https://cloud.githubusercontent.com/assets/939894/14989199/b2dbcade-1124-11e6-8062-80c83817d680.png)

The only strange this is that after hitting the reload icon,  the message only says "zone Reload Results" and the OK button.

**Comment by aredan** [comment] 2016-05-03 15:51
"I created the zone today and the Serial is always 2015050300." _and_ added records just to force the Serial to increment.

The new records are in the server /zones/master/db.antigua.pw but the Serial is the same as the first build.

**Comment by WillyXJ** [comment] 2016-05-03 16:17
This output looks like the reload is not actually occurring on your clients.  There are a few things to check:

1. During your zone reload, what does /var/log/fm.log show on your DNS servers?
2. Can you please ensure Settings -> General -> Show Errors is enabled.  Once enabled, see if there are any PHP errors displayed during the reload.
3. What update method are you using with your DNS servers?
4. Try running the reload manually on your DNS servers with:

`sudo php /usr/local/facileManager/fmDNS/client.php zones id=14 debug`

**Comment by aredan** [comment] 2016-05-03 18:05
1. 
![2016-05-03 12_16_37-remote desktop manager free jumper](https://cloud.githubusercontent.com/assets/939894/14990275/d90a7d22-1129-11e6-8176-f2c1e7a5d45a.png)

2. Yes "Show Errors" is enable. I cant see any errors.

3. HTTP.

4. 
![2016-05-03 13_54_26-remote desktop manager free jumper](https://cloud.githubusercontent.com/assets/939894/14993184/a017bfe4-1137-11e6-8ceb-e0cff53023be.png)

In this image you can see that the Serial change from 00 -> 01 this was triggered by me applying a SOA template, but, that SOA Template have the following values:

![2016-05-03 13_56_58-soa templates facilemanager](https://cloud.githubusercontent.com/assets/939894/14993232/dd1b14e0-1137-11e6-9f62-873761b68acd.png)

This is my dashboard right now"

![2016-05-03 13_57_47-dashboard facilemanager](https://cloud.githubusercontent.com/assets/939894/14993261/00097064-1138-11e6-89ad-c9f056ef56b9.png)


Right now I'm installing on another VM at work so I can see if this is replicated here.

**Comment by WillyXJ** [comment] 2016-05-03 18:31
Thank you for this information.  I've been able to reproduce it using the HTTP update method.  A fix should come soon.

**Comment by WillyXJ** [comment] 2016-05-03 18:51
You can manually apply the change to your DNS servers (client app) from https://github.com/WillyXJ/facileManager/commit/35d196a6f242db9c73cc2f0cd5ccd9b488142aa5 or wait until the next release.

**Comment by aredan** [comment] 2016-05-03 19:31
I manually apply the change in my two nameserver.

First, I failed to mention that when I did a change in the Forward zone (adding a A record) the Serial didn't increase locally, I mean, when I click "Preview Config" the Serial still the same. 

![2016-05-03 15_11_49-server config preview facilemanager](https://cloud.githubusercontent.com/assets/939894/14995548/53d19770-1143-11e6-98cb-d30fbf8b305d.png)
* Fix applied.

![2016-05-03 15_14_27-greenshot capture form](https://cloud.githubusercontent.com/assets/939894/14995563/6728f656-1143-11e6-9118-5b28b74548ac.png)

*Reload clicked.

![2016-05-03 15_15_07-server config preview facilemanager](https://cloud.githubusercontent.com/assets/939894/14995575/7a5f8a14-1143-11e6-99fb-058bdcdbb179.png)
*Serial still the same when Preview Config in the Zones->Forward.

![2016-05-03 15_16_37-remote desktop manager free jumper](https://cloud.githubusercontent.com/assets/939894/14995601/9bafca76-1143-11e6-8926-50d45a5e8eed.png)
*fm.log errors.


![2016-05-03 15_24_15-name servers facilemanager](https://cloud.githubusercontent.com/assets/939894/14995671/0d8f69f8-1144-11e6-97e1-755dfbb4e3eb.png)
![2016-05-03 15_23_45-remote desktop manager free jumper](https://cloud.githubusercontent.com/assets/939894/14995674/12be7716-1144-11e6-9edd-991dc9e37eec.png)

*If do a rebuild config to both servers.

**Comment by WillyXJ** [comment] 2016-05-03 20:59
The serial number does not increment until after a successful reload on all servers configured to host the zone.  In your case, it looks like it failed on odin.aanetworks.org and because of this failure the serial number did not increment.

You can verify the serial number increment by disabling odin.aanetworks.org in the Config -> Servers page, add/modify a record, and reload the zone.

Why odin.aanetworks.org is throwing an error on the reload is a separate issue.  Is that zone configured to be hosted on "All Servers", a server group, or individual servers?  I'm wondering if you've hit another bug as that error, in theory, should never appear when using the web interface.  It might be easier to send me the output of the following database query:

```
SELECT `domain_name`,`domain_name_servers` FROM `fm_dns_domains` WHERE `domain_id`=6;
```

**Comment by aredan** [comment] 2016-05-04 00:21
odin is set at the Zone template level. As you describe, if I remove odin the reload is send and the Serial is update everywhere.

This is the output of the SQL query.
![2016-05-03 20_19_38-cortana](https://cloud.githubusercontent.com/assets/939894/15002171/6cd012d2-116c-11e6-917b-55b30194dbd5.jpg)

I remove odin from my configuration for the the moment, I will try to add a 3er server that was running all my zones to see if the same error appear.

**Comment by aredan** [comment] 2016-05-04 02:02
Removed the server, delete de config.inc.php and reinstalled the client the error keeps showing.
Something weird is that I made a group with leela and odin.

![2016-05-03 21_59_24-name servers facilemanager](https://cloud.githubusercontent.com/assets/939894/15003489/611a8216-117a-11e6-88a1-30e99e438fda.jpg)

created a brand new zone for testing and configured that zone to used the group insted of individual servers and the error goes away, everything works as expected.

![2016-05-03 22_01_15-reverse zones facilemanager](https://cloud.githubusercontent.com/assets/939894/15003505/960ec13a-117a-11e6-83f0-2f80102d915d.jpg)

**Comment by WillyXJ** [comment] 2016-05-04 15:21
Thank you for the additional information and your patience.  I've confirmed this bug when individual servers are selected to serve the zone.

**Comment by WillyXJ** [comment] 2016-05-04 15:45
Fix has been submitted.  Either wait for the next release or manually apply the change to class_buildconf.php from https://github.com/WillyXJ/facileManager/commit/ee6deab1ced41c855f50dee169fe664c6981cfd0

**Comment by WillyXJ** [comment] 2016-05-06 02:44
v2.2.2 has been released with both of these fixes.

**Closed by WillyXJ** 2016-05-06 02:44 UTC
Labels: Bug, fmDNS
