### ISSUE TITLE
Support of dynamic zones (freeze/thaw)

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#190] opened 2015-03-18 15:16 UTC
I noticed today that for proper freeze/thaw support there is some more work to be done. When a dynamic update to a zone happened bind will automatically update the serial number and the contents of that file. So in effect we are overwriting the dynamic changes when we trigger a config rebuild.

In my opinion we should have the following activities for reload/buildconf: freeze, figure out which zones are dynamic, read the necessary information off that zone and post them back to fM, update all configuration, reload, thaw.

**Comment by WillyXJ** [comment] 2015-03-18 16:14
This is a duplicate of #90.

**Closed by WillyXJ** 2015-03-18 16:14 UTC
Labels: Duplicate, fmDNS
