### ISSUE TITLE
[ISSUE] Error Import Verification when editing a dynamic update zone

### ISSUE THREAD

**Issue by fruza** [WillyXJ/facileManager#445] opened 2019-05-21 11:05 UTC
fM Version : **3.4.1**
fmDNS Version : **3.3.3**

Hi!, I've configured a dynamic update zone and when I try to edit the zone, facilemanager does an import verification and always give me the following error:

![ErrorDDNS](https://user-images.githubusercontent.com/31692524/58090983-c9279180-7bc8-11e9-9c78-b7bc756f8bab.png)

I've read the #370 issue which is similar but for an older release. I'm using fmDNS 3.3.3 and I don't know what I'm doing wrong.

Regards, Fernando.

**Comment by WillyXJ** [comment] 2019-05-21 16:21
Hi Fernando,

Are you able to provide the contents of your zone file from your DNS server?  I'm only interested in the NS records so I can see how they are formatted before fmDNS wants to import them.  So far, I'm not able to reproduce this issue.

**Comment by fruza** [comment] 2019-05-22 09:28
Yes, of course. These are the name servers for this zone. They are the same for all zones I have got:

![Captura de pantalla de 2019-05-22 10-20-31](https://user-images.githubusercontent.com/31692524/58159363-9dfe7a00-7c7c-11e9-899d-959cc2964528.png)

`===========================================================================`
`/etc/named/zones/master/db.gaecu.sescam.jclm.es.hosts:`
`===========================================================================`
`; This file was built using fmDNS 3.3.3 on Wed, 22 May 2019 10:31:03 +0200 Europe/Madrid`

`$TTL 1d`
`gaecu.sescam.jclm.es. IN SOA dnstomaster.sescam.jclm.es.`
`sistemas_infraestructuras.ati.sescam.jccm.es. (`
`		2019052118	; Serial`
`		2h		; Refresh`
`		1h		; Retry`
`		2w		; Expire`
`		1d )		; Negative caching of TTL`

`; Name servers`
`gaecu.sescam.jclm.es.       8   IN   NS   ns1.sescam.jclm.es.`
`gaecu.sescam.jclm.es.       8   IN   NS   ns2.sescam.jclm.es.`
`gaecu.sescam.jclm.es.       8   IN   NS   ns3.sescam.jclm.es.`
`gaecu.sescam.jclm.es.       8   IN   NS   ns4.sescam.jclm.es.`

Then in sescam.jclm.es zone I've got the A records for the name servers:

`ns1.sescam.jclm.es.         8   IN   A   192.168.100.4 ; dnstomaster`
`ns2.sescam.jclm.es.         8   IN   A   192.168.100.5 ; dnstodes`
`ns3.sescam.jclm.es.         8   IN   A   192.168.110.15 ; dnsabdes`
`ns4.sescam.jclm.es.         8   IN   A   192.168.120.25 ; dnscrdes`

If I query with dig for the name servers I get:

`[root@dnstomaster ~]# dig NS gaecu.sescam.jclm.es`

`; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> NS gaecu.sescam.jclm.es`
`;; global options: +cmd`
`;; Got answer:`
`;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21296`
`;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 5`

`;; OPT PSEUDOSECTION:`
`; EDNS: version: 0, flags:; udp: 4096`
`;; QUESTION SECTION:`
`;gaecu.sescam.jclm.es.		IN	NS`

`;; ANSWER SECTION:`
`gaecu.sescam.jclm.es.	8	IN	NS	ns1.sescam.jclm.es.`
`gaecu.sescam.jclm.es.	8	IN	NS	ns3.sescam.jclm.es.`
`gaecu.sescam.jclm.es.	8	IN	NS	ns4.sescam.jclm.es.`
`gaecu.sescam.jclm.es.	8	IN	NS	ns2.sescam.jclm.es.`

`;; ADDITIONAL SECTION:`
`ns1.sescam.jclm.es.	8	IN	A	192.168.100.4`
`ns2.sescam.jclm.es.	8	IN	A	192.168.100.5`
`ns3.sescam.jclm.es.	8	IN	A	192.168.110.15`
`ns4.sescam.jclm.es.	8	IN	A	192.168.120.25`

`;; Query time: 1 msec`
`;; SERVER: 127.0.0.1#53(127.0.0.1)`
`;; WHEN: mié may 22 11:06:36 CEST 2019`
`;; MSG SIZE  rcvd: 185`

Everything seems to be right however when I edit gaecu.sescam.jclm.es zone I get the error in the import verification.

Regards, Fernando.

**Comment by WillyXJ** [comment] 2019-05-22 14:51
Thanks for the additional information.  I'm now able to reproduce this bug and will get a fix for it.

**Comment by WillyXJ** [comment] 2019-10-02 00:13
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2019-10-02 00:13 UTC
Labels: Confirmed Bug, Fixed in next release, fmDNS
