### ISSUE TITLE
[ISSUE] Error zones.conf.all: file not found appear in preview configuration when recursion enabled

### ISSUE THREAD

**Issue by andzham** [WillyXJ/facileManager#572] opened 2023-03-07 22:52 UTC
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.3.0**
<fmDNS> Version : **5.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
no error/warning shows up when recursion set to enabled

**(BUG | ISSUE) Actual Behavior:**
with recursion set to yes in server options warning %zonesdir/zones.conf.all appears in configuration preview before roothints

**(BUG | ISSUE) Steps to reproduce:**

add option recursion yes and after that press preview configuration
warning about zones.conf.all file not found shown in configuration preview window
with recursion set to no  - all ok

**Comment by WillyXJ** [comment] 2023-03-08 16:14
I'm currently unable to reproduce this issue. Would you please provide a screenshot of the error?

**Comment by andzham** [comment] 2023-03-09 00:32
Screens of issue from configuration preview window:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/51474164/223881802-afef0ef9-90a0-4473-8fc1-3ea6c0d344ab.png">

<img width="685" alt="image" src="https://user-images.githubusercontent.com/51474164/223882075-80c566e1-6a5e-4609-b636-410f5947dc08.png">

Additional information:
we have views defined for other server ( at server levvel) in same instance of fmDNS, but no views defined for server at question, as well we are just trying to get initial configuration build ready, so server is currently disabled.
if we assign views to server in question - no error anymore ( of course instead of zones.conf.all  zone conf files for views are created)
in other instance of fmDNS where no views used at all, enabling recursion for some indivvidual server doesn't cause metioned error

**Comment by WillyXJ** [comment] 2023-03-09 15:26
Thanks for the screen grabs. I see now the message for you comes from the named checks.  However, I'm still unable to reproduce this.  Here are my steps:

1. Fresh installation with two name servers (test-server1 and test-server2)
2. Enable named checks in the settings
3. Views -> Select test-server1 from the servers list
4. Create view (test-view) only for test-server1
5. Create zone in All Views, but associate it with test-server1
6. Preview the config individually for both servers and I'm not getting that message.

What additional steps do I need to take?

In addition, can you confirm your config preview does not have any file named "zones.conf.all" in it?

**Comment by andzham** [comment] 2023-03-09 16:08
For your test setup after step 4.
Config -> Options -> All views, Select test-server2 -> Add new Global Option -> Option Name : Recursion, Option value: Yes
for step 5. Create zone in test-view associating it with test-server1
proceed with step 6 and for test-server2 error/warning message are show up
and yes confirm there is no file zones.conf.all in preview apart of red colored include directive, as shown in previous screen grab.

**Comment by WillyXJ** [comment] 2023-03-09 18:52
Hmmm even with those steps I'm still getting a good config.  Your config preview does not have zones.conf.all, but does it have zones.conf.<view name> instead?  Or maybe you don't have any zone definition files in the preview.

**Comment by WillyXJ** [comment] 2023-03-09 19:04
If I delete the default zones (localhost, 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, and 0.0.127.in-addr.arpa) then I'm able to get the error.

Until the next release comes with the fix, you can create a dummy zone that doesn't have a SOA and/or NS records as a workaround.  This dummy zone will exist in the database, but won't get built on any of your servers, but it will allow zones.conf.all to be built.

**Comment by WillyXJ** [comment] 2023-03-10 00:18
This is now fixed in [fmDNS 5.3.0](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2023-03-10 00:18 UTC
Labels: Confirmed Bug, fmDNS, Fixed in next release
