### ISSUE TITLE
[ISSUE] Cannot Import Zone Files

### ISSUE THREAD

**Issue by kclinsd** [WillyXJ/facileManager#633] opened 2024-07-02 07:46 UTC
fM Version :  v4.6.2
fmDNS Version :  v6.0.5

Ubuntu 24.04 LTS
PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
Server version: Apache/2.4.58 (Ubuntu)
Server built:   2024-04-18T15:13:41
Mysql 8.0

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I can use the import zone files feature.

**(BUG | ISSUE) Actual Behavior:**
I can't use the import zone files feature, after selecting the file to import and selecting the import zone I can press the import zones button, but there are no other options and the zone cannot be imported successfully.
I have checked the logs from apache error.log and access.log but did not find any useful clues.

**(BUG | ISSUE) Steps to reproduce:**
Fresh install from this repository using Ubuntu 24.04 LTS, PHP 8.3, Apache/2.4, and MySQL 8.

**Comment by kclinsd** [comment] 2024-07-02 08:09
After seeing that there was an update for the fmDNS v6.0.6 module at https://www.facilemanager.com/modules/fmdns/, I tried to upgrade the fmDNS module. After successfully upgrading, it turned out that it was still the same and still couldn't import zones

**Comment by WillyXJ** [comment] 2024-07-03 03:06
Besides not importing your zone file, what is the user experience? Any errors? Any blank screens? How long do you wait? How many records are in the file you are importing?

**Comment by kclinsd** [comment] 2024-07-03 03:29
I only tried for 2 zones and each zone contained 10 records. When just importing records it also doesn't work. After clicking the import record/zone button, the page immediately returns to the same page. Data is not imported at all.

**Comment by kclinsd** [comment] 2024-07-03 03:52
The issue is like this
![ezgif-3-b5248cfd91](https://github.com/WillyXJ/facileManager/assets/16216378/9d559619-0616-46b3-8b2a-4ee61f61ca56)

**Comment by WillyXJ** [comment] 2024-07-03 12:49
It looks like you aren't selecting the zone to import the data into -- you need to select the zone as well.

**Comment by kclinsd** [comment] 2024-07-03 12:54
Still the same, I have tried selecting zone but it still doesn't work

**Comment by WillyXJ** [comment] 2024-07-03 13:49
I'm able to reproduce it now. It seems to be a bug introduced in 6.0.5. Feel free to install [v6.0.4](https://www.facilemanager.com/download/module/fmdns-6.0.4.tar.gz) until a fix is released.

**Comment by kclinsd** [comment] 2024-07-04 00:57
It seems like the bug is in facileManager v4.6.2, because I tried using facileManager v4.6.1 with fmDNS v6.0.6 the import menu can work.

**Comment by WillyXJ** [comment] 2024-07-08 14:16
Thanks for the additional testing and report. This should be fixed in the next release of fM.

**Comment by imyller** [comment] 2024-08-27 07:17
@WillyXJ could you please consider making an interim release for fmDNS and core soon?

**Comment by WillyXJ** [comment] 2024-08-27 23:51
Beta1 of the core and all modules is now available.  I'm hoping to get a stable release out in October.

![image](https://github.com/user-attachments/assets/b8cd168b-d8fb-441b-bf6f-1fa915f3ec8d)

**Comment by WillyXJ** [comment] 2024-09-30 15:30
This is now fixed in [fM 4.7.0](http://www.facilemanager.com/download/) and later.

**Closed by WillyXJ** 2024-09-30 15:30 UTC
Labels: Confirmed Bug, fmDNS, fM Core, Fixed in next release
