### ISSUE TITLE
[BUG] Pool Configuration ignores ("forgets") peer group selection

### ISSUE THREAD

**Issue by shake-spear** [WillyXJ/facileManager#480] opened 2020-03-16 08:26 UTC
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **v3.5.7**
fmDHCP Version : **0.4.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

(a) Select an existing and enabled failover peer (called "<Peer Name>") on the "Pools Edit Config" of a pool
(b) Press "Save"
(c) Reopen "Pools Edit Config" of the same pool

=>
(I) The previously selected failover peer "<Peer Name>" should be shown in the Drop-Down Box "Failover Peer"
(II) In the generated DHCP configfile the pool section of the mentioned pool should contain the line "failover peer <Peer Name>;"
	pool {
                failover peer <Peer Name>;
		range 192.168.128.180 192.168.128.199;
		default-lease-time 3600;
		max-lease-time 86400;
		allow unknown-clients;
	}

**(BUG | ISSUE) Actual Behavior:**

(I) Drop-Down Box is empty
(II) line "failover peer "<Peer Name>"; is missing in generated configfile
	pool {
		range 192.168.128.180 192.168.128.199;
		default-lease-time 3600;
		max-lease-time 86400;
		allow unknown-clients;
	}

**(BUG | ISSUE) Steps to reproduce:**

(a) Select an existing and enabled failover peer (called "<Peer Name>") on the "Pools Edit Config" of a pool
(b) Press "Save"
(c) Reopen "Pools Edit Config" of the same pool

**Comment by WillyXJ** [comment] 2020-03-16 19:58
I'm not able to reproduce this as I cannot create a peer without a name.  Were you able to create an unnamed peer or is this as a result from an upgrade?

**Comment by shake-spear** [comment] 2020-03-20 16:24
Oops - sry. During Copy&Paste the string enclosed by the double quotes got removed - silly me.
The peer has a name. The removed string was `<peername>` :)

**Comment by WillyXJ** [comment] 2020-03-20 19:38
Got it and I'm able to reproduce it. Thanks.

**Comment by WillyXJ** [comment] 2020-03-20 19:55
Would you please confirm that you've upgraded fmDHCP at least once or if this is a new installation of 0.4.4?

**Comment by shake-spear** [comment] 2020-03-21 09:38
Yes - I upgraded once 
from 
       facilemanager-complete-3.5.6.tar.gz
to
       facilemanager-complete-3.5.7.tar.gz

But I *think* (can't remember exactly anymore) I created the pools the first time with 0.4.4 - but this memory is blurry :)

**Comment by WillyXJ** [comment] 2020-10-24 00:09
This is now fixed in [fmDHCP 0.4.5](http://www.facilemanager.com/modules/fmdhcp/) and later.

**Closed by WillyXJ** 2020-10-24 00:09 UTC
Labels: Confirmed Bug, Fixed in next release, fmDHCP
