### ISSUE TITLE
[FEATURE REQUEST] rename zone files

### ISSUE THREAD

**Issue by bstall23** [WillyXJ/facileManager#456] opened 2019-08-29 18:03 UTC
fmDNS creates zone files as 'db.example.com.hosts.'

**I would like to know if there is a way to change the hard coded way fmDNS names its zone files?** 

 The reason for this is so zone files from fmDNS meets the standardized naming scheme already in place at work The way it is named at work is "example.com.zone"

Any help would be appreciated

**Comment by WillyXJ** [comment] 2019-08-30 12:15
Zone file names are not changeable without changing it in the code.  Of course, if you do that, then any upgrades will wipe out your changes.

**Comment by bstall23** [comment] 2019-08-30 15:52
I did figured out how to do it by modifying class_buildconf.php. 

By the way the code is written, you have it hard coded to append ‘db.’ and ‘.hosts’ in several locations. Would it be a possible to make these variables that can be changed from the top of the file fairly easily after an upgrade?
 
Ultimately it would be nice to customize this froM the tool but can deal with modifying the .php

**Comment by WillyXJ** [comment] 2019-08-30 16:51
I'll change this to a feature request for the zone file names to be configurable.

**Comment by WillyXJ** [comment] 2019-10-02 00:13
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.

**Closed by WillyXJ** 2019-10-02 00:13 UTC
Labels: Feature Request, Fixed in next release, fmDNS

**Comment by susanin-ivan** [comment] 2021-02-17 09:02
Hi,

It looks like this change introduced file naming bug - if default_value is 'db.{ZONENAME}.hosts', then slave zone file names become:

-       file "/etc/named/zones/slave/db.0.0.20.in-addr.arpa**.0.**rev";
+       file "/etc/named/zones/slave/db.0.0.20.in-addr.arpa**0..**hosts";

-       file "/etc/named/zones/slave/db.zone.com**.0.**hosts";
+       file "/etc/named/zones/slave/db.zone.com**0..**hosts";

Master zones naming is not affected:

-       file "/etc/named/zones/master/db.0.0.127.in-addr.arpa.rev";
+       file "/etc/named/zones/master/db.0.0.127.in-addr.arpa.hosts";

Thank you!

**Comment by WillyXJ** [comment] 2021-02-18 15:47
@susanin-ivan Confirmed and fixed in next release.
